### ISSUE TITLE
weblogo error

### ISSUE THREAD

**Issue by osallou** [bioconda/bioconda-recipes#2167] opened 2016-08-18 09:57 UTC
weblogo install on a Debian is ok, but it fails to run due to missing perl modules:

    root@6b0eb9328ff0:/# conda install -y weblogo
    ...
    The following NEW packages will be INSTALLED:
    
        ruamel_yaml: 0.11.14-py35_0
        weblogo:     2.8.2-2       
    
    The following packages will be UPDATED:
    
        conda:       4.0.5-py35_0 --> 4.1.11-py35_0 
        conda-env:   2.4.5-py35_0 --> 2.5.1-py35_0  
        python:      3.5.1-0      --> 3.5.2-0       
        sqlite:      3.9.2-0      --> 3.13.0-0      
        xz:          5.0.5-1      --> 5.2.2-0 
    ....

    root@6b0eb9328ff0:/# seqlogo
    Can't locate FindBin.pm in @INC (you may need to install the FindBin module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at /root/miniconda3/bin/../share/weblogo-2.8.2-2/seqlogo line 63.
    BEGIN failed--compilation aborted at /root/miniconda3/bin/../share/weblogo-2.8.2-2/seqlogo line 63.

**Comment by yhoogstrate** [comment] 2016-08-26 14:12
Could you try adding:
```
requirements:
  run:
      - perl-threaded
```

to this file: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/weblogo/meta.yaml

and follow the build instructions to test (https://github.com/bioconda/bioconda-recipes#step-2-test-the-recipe)

**Comment by osallou** [comment] 2016-08-29 17:48
I gonna try, but this is not the first bioconda package failing to run due to missing deps. I wonder how packages are tested before being put in available packages. Packaging is a hard task, but here I faced several packages not running at all.... :-(

**Comment by daler** [comment] 2016-08-30 14:07
I'm unable to reproduce on the `continuumio/miniconda3` docker container, which is debian 8.5:

```bash
docker pull continuumio/miniconda3
docker run -it continuumio/miniconda3
conda install -y -c bioconda weblogo
seqlogo
# 
# input file not specified, terminating...
# 
# usage: seqlogo -f <input filename> [OPTIONs with values]
# Creates a logo for the given input filename.
# ...
```
Based on your prompt you might be running docker as well -- can you share your docker image or dockerfile? As for your question about tests, [these test commands](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/weblogo/meta.yaml#L16) must pass before anything is uploaded to anaconda.

You mention you've had other packages not running at all; were these bioconda packages?

**Comment by osallou** [comment] 2016-08-30 15:37
I am indeed using Docker (osallou/bioconda). I'm fine to use continuumio/miniconda3 instead, but it should have no impact. Or it is a conda version issue with wrong management in dependencies... (but we see in logs that conda is updated too).

Other packages were bioconda ones (see #2166)

**Comment by daler** [comment] 2016-08-30 16:11
Thanks, I can reproduce with that. The big differences is that it's based on the stripped-down busybox rather than the full debian used by continuumio/miniconda3. As @yhoogstrate mentioned, adding `perl-threaded` should fix this recipe, though it might need some other as-yet-unknown dependencies.

@jerowe, here's an example of a package that depends on perl but we wouldn't otherwise know since it's not listed in any dependencies. Have to figure out how to detect these. @johanneskoester we were considering using busybox at some point for building; might we be able to use it (or alpine) for testing to catch cases like this?

**Comment by osallou** [comment] 2016-08-30 16:59
Busybox and alpine are *good* base images to test such issues as they are
with almost nothing installed... ;-)

In the meanwhile i will try with continuum debian based image

**Comment by daler** [comment] 2016-08-30 21:33
Agreed, while it would be hard to build on those images, it would be great to test on them.

Looking more closely at the weblogo recipe, it's for the original perl version 2 which hasn't been updated in 11 years (!). @percyfal, looks like you were the one to add this originally back in the early days of bioconda; any objections to updating to 3.5? I can move the existing 2.8.2 recipe to a subdir and make the default version 3.5.

**Comment by bgruening** [comment] 2016-08-31 17:22
Indeed we are very close to test everything in busybox as soon as I got mulled to autobuild docker container for us. Mulled is using busybox and already found a few errors. Will write more about this as soon as I'm back from vacation.

**Comment by bgruening** [comment] 2016-10-09 11:46
I will close this now. @osallou please feel free to reopen if you still have problems.

**Closed by bgruening** 2016-10-09 11:46 UTC

**Comment by osallou** [comment] 2016-10-10 04:40
As it is used for your test infra, i agree it is not a bug. But i feel it
sad that package test command is not a reusable command, be it by an other
system or simply a user  wishing to test/validate the install.

Le dim. 9 oct. 2016 13:46, Björn Grüning <notifications@github.com> a
écrit :

**Comment by bgruening** [comment] 2016-10-10 07:01
@osallou it is very reusable, thats the aim of $R. You can reuse it on Win, OSX and Linux you just need to implement the meaning of $R depending on your platform.
