### ISSUE TITLE
SAVAGE recipe does not specify boost version 

### ISSUE THREAD

**Issue by nekrut** [bioconda/bioconda-recipes#11007] opened 2018-09-18 14:37 UTC
savage cannot be run after installation due to this error:

```
undefined symbol: _ZN5boost15program_options3argE
```
thus savage package is effectively useless

**Comment by epruesse** [comment] 2018-09-20 02:55
@nekrut Can you try to fix it? 

ping @jbaaijens (author of savage)

**Comment by epruesse** [comment] 2018-09-20 03:15
@nekrut I cannot reproduce your linker error. Please elaborate on how you arrived at there.

**Comment by chapmanb** [comment] 2018-09-20 14:29
I've hit this problem with Delly as well, and it typically occurs when the recipe was compiled against a different boost than you end up installing. Things are a bit hairy with boost at the moment, as the conda-forge boost doesn't compile correctly with the new compilers. For recipes that had issues what I've done is swap to use libboost and to ensure we're compiling with the gcc conda-forge compilers. Here's my latest delly fix to work around the problem: #11035.

Anton, it would probably be helpful to know what savage and boost versions you have in your environment. I don't know much about savage but maybe re-compiling it the way I've done with delly would help avoid the issue.

**Comment by jbaaijens** [comment] 2019-02-25 14:37
@nekrut I'm about to upload a new version of savage to bioconda and I would be happy to fix this boost issue. I can't reproduce the error though...

@chapmanb Thanks for thinking along. Do I understand correctly that your suggestion is to replace boost by libboost in the meta.yaml file? Won't this lead to any new issues? And then, how do I test if it works? I'm not familiar with this at all, sorry.

**Comment by chapmanb** [comment] 2019-02-25 14:44
Sorry, I'm not sure my comment is still relevant/useful since conda-forge and bioconda have been completely migrated to the new compilers. I haven't done a boost compile since then so not sure what to recommend, but my practical suggestion would be to try with boost again and hopefully it'll just work now that everything has been ported.

**Comment by jbaaijens** [comment] 2019-02-25 15:31
Ok, thanks, I'll just try then :)

**Comment by jbaaijens** [comment] 2019-03-01 15:48
I've updated the recipe to savage version 0.4.1 but it doesn't compile. It seems to have something to do with boost: https://circleci.com/gh/bioconda/bioconda-recipes/46101

I'm not sure how to fix this, any help would be very much appreciated!

**Comment by jbaaijens** [comment] 2019-03-04 11:36
@bioconda/core Could you help me getting savage compiled?

**Comment by johanneskoester** [comment] 2019-03-04 11:41
@jbaaijens could you open a pull request with the changes? This way, it will be easier for us to diagnose the problem and discuss solutions.

**Comment by jbaaijens** [comment] 2019-03-04 13:02
Oh ok, done!

**Comment by johanneskoester** [comment] 2019-03-05 15:37
Fixed with PR #13893.

**Comment by johanneskoester** [comment] 2019-03-05 15:38
@chapmanb we were able to use boost from conda-forge. I just had to ensure that the correct cxx is used and I had to pass the library path with -L.

**Closed by johanneskoester** 2019-03-05 15:37 UTC

**Comment by chapmanb** [comment] 2019-03-06 10:28
Nice one, thanks for the heads up on boost working without any changes again. That's great news and I'll swap over all my recipes when they get updates. Thanks again for testing this all out.
