### ISSUE TITLE
circleci fails and scripts do not run on macOS

### ISSUE THREAD

**Issue by widdowquinn** [bioconda/bioconda-recipes#13932] opened 2019-03-06 17:03 UTC
I'm following the guides at:

- [https://bioconda.github.io/contrib-setup.html](https://bioconda.github.io/contrib-setup.html)
- [https://bioconda.github.io/contribute-a-recipe.html](https://bioconda.github.io/contribute-a-recipe.html)

while trying to bump the version of a recipe I've previously contributed. The steps in the guide for local testing are failing for me in various ways.

I'm probably doing something daft, have overlooked a step, or have some incompatibility somewhere - but I can't see what. Any help/advice would be gratefully received.

## Steps to reproduce:

- Fork [https://github.com/bioconda/bioconda-recipes](https://github.com/bioconda/bioconda-recipes) to own GitHub account
- Then clone the repo and setup:

```bash
git clone https://github.com/<username>/bioconda-recipes.git
cd bioconda-recipes
git remote add upstream https://github.com/bioconda/bioconda-recipes.git
git checkout master
git pull upstream master
git push origin master
git checkout -b <package>
```

- Make version number and hash change in `meta.yaml`
- `git add` and `git commit` the modified file

### Problem 1: CircleCI tests do not run

```bash
docker pull bioconda/bioconda-utils-build-env
circleci build
```

- Expected result: CircleCI tests run
- Observed result:

```bash
$ circleci build
Docker image digest: sha256:65b2102646d5658f892e0ad8253b7912c676126c857c87c8c12460f0aa4f5aa1
====>> Spin up Environment
Build-agent version 1.0.8563-43047892 (2019-03-06T15:11:54+0000)
Starting container bioconda/bioconda-utils-build-env
  using image bioconda/bioconda-utils-build-env@sha256:1f62a95df52ff1f900f14e391d2925f400d97463c2071f840b0d649a7a5af088

Using build environment variables
  BASH_ENV=/tmp/.bash_env-localbuild-1551890040
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=pyani
  CIRCLE_BUILD_NUM=
  CIRCLE_JOB=build
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_REPOSITORY_URL=https://github.com/widdowquinn/bioconda-recipes.git
  CIRCLE_SHA1=4e42d36a20e979535651040bd28505bc39adb20d
  CIRCLE_SHELL_ENV=/tmp/.bash_env-localbuild-1551890040
  CIRCLE_WORKING_DIRECTORY=~/project

====>> Checkout code
  #!/bin/bash -eo pipefail
mkdir -p /root/project && cd /tmp/_circleci_local_build_repo && git ls-files -z | xargs -0 tar -c | tar -x -C /root/project && cp -a /tmp/_circleci_local_build_repo/.git /root/project
/bin/bash: git: command not found
tar: Cowardly refusing to create an empty archive
Try `tar --help' or `tar --usage' for more information.
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
Error: Exited with code 2
Step failed
Error: runner failed
{"Runner":true,"level":"error","msg":"runner failed","task-id":"localbuild-1551890040","time":"2019-03-06T16:34:04Z"}
Task failed
Error: task failed
```

### Problem 2: `bootstrap.py` script fails

- Attempt to use `./bootstrap.py`:

```bash
./bootstrap.py /tmp/miniconda
```

- Expected result: miniconda environment builds
- Actual result: script reports non-zero exit from `.circleci/setup.sh`

```bash
$ ./bootstrap.py /tmp/miniconda
From https://github.com/bioconda/bioconda-recipes
 * [new branch]          master     -> __upstream__Tduwgrl00C/master
Setting up bioconda-utils...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 34.9M  100 34.9M    0     0  2139k      0  0:00:16  0:00:16 --:--:-- 2476k
ERROR: File or directory already exists: '/tmp/miniconda/miniconda'
If you want to update an existing installation, use the -u option.
Traceback (most recent call last):
  File "./bootstrap.py", line 110, in <module>
    sp.check_call(['.circleci/setup.sh'], env=env)
  File "/Users/lpritc/.pyenv/versions/3.6.3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['.circleci/setup.sh']' returned non-zero exit status 1.
```

However, running `.circleci/setup.sh` directly from the shell exists with zero status:

```bash
$ .circleci/setup.sh 
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 11 (delta 5), reused 4 (delta 3), pack-reused 0
Unpacking objects: 100% (11/11), done.
From https://github.com/bioconda/bioconda-recipes
 * [new branch]          master     -> __upstream__SphvG78nmH/master
Setting up bioconda-utils...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 34.9M  100 34.9M    0     0  1993k      0  0:00:17  0:00:17 --:--:--  930k
[...]
$ echo $?
0
```

Likewise when running from a Python interpreter:

```bash
$ python
Python 3.6.3 (default, Mar  6 2019, 15:10:06) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> subprocess.run([".circleci/setup.sh"])
From https://github.com/bioconda/bioconda-recipes
 * [new branch]          master     -> __upstream__LvG3fdBlje/master
bioconda-utils is /Users/lpritc/Development/GitHub/bioconda-recipes/miniconda/bin/bioconda-utils
CompletedProcess(args=['.circleci/setup.sh'], returncode=0)
```

### Relevant details

- OS: macOS 10.14.3
- Python 3.6.3 (via `pyenv`) 
- circleci version 0.1.5432+9ea4b64
- docker version 18.03.0-ce

```bash
$ docker images
REPOSITORY                                      TAG                 IMAGE ID            CREATED             SIZE
circleci/picard                                 <none>              542cf60a44f1        2 hours ago         103MB
bioconda/bioconda-utils-build-env               latest              5c934ac5aa08        29 hours ago        3GB
```

**Comment by nfahlgren** [comment] 2019-03-12 21:02
I'm seeing these issues as well #13974

**Comment by davebx** [comment] 2019-03-14 14:57
I can confirm that Problem 1 also occurs in an ubuntu 18.10 installation I created yesterday.

**Comment by grimbough** [comment] 2019-03-18 15:59
I'm experiencing these problems with local CircleCI too.

OS: Linux Mint 19.0
circleci version: 0.1.5490+82d3083
docker version: 18.09.3

```
-> % docker images
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
bioconda/bioconda-utils-build-env   latest              0f19ee9ac161        11 hours ago        2.88GB
circleci/picard                     latest              cf6b57e111ff        3 days ago          103MB
```

**Comment by simonbray** [comment] 2019-03-29 15:12
Did anyone find a solution? I'm experiencing an identical problem with CircleCI.

**Comment by crashfrog** [comment] 2019-04-01 15:06
I'm seeing this in current builds of `bioconda-utils-build-env`

```
$ docker images
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
circleci/picard                     latest              960b0d4d030f        3 hours ago         103MB
bioconda/bioconda-utils-build-env   latest              566c11a3439b        15 hours ago        2.86GB

$ circleci build
Docker image digest: sha256:8724b09110aa5ad5f661447ca4c15ef46d699032166319ffa7fb9a625c973a7b
====>> Spin up Environment
Build-agent version 1.0.9934-d6876d00 (2019-04-01T12:08:20+0000)
Docker Engine Version: 18.09.1
Kernel Version: Linux c769cdcc68a8 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 Linux
Starting container bioconda/bioconda-utils-build-env
  using image bioconda/bioconda-utils-build-env@sha256:bde46af51d726d559a3c091ec149d2d2306c1a748a8caa2448a50d76aaf256b1

Using build environment variables
  BASH_ENV=/tmp/.bash_env-localbuild-1554130930
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=shigatyper
  CIRCLE_BUILD_NUM=
  CIRCLE_JOB=build
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_REPOSITORY_URL=https://github.com/CFSAN-Biostatistics/bioconda-recipes.git
  CIRCLE_SHA1=4186a3e68b37295c476bbf0c96a5fd2bc31bb59a
  CIRCLE_SHELL_ENV=/tmp/.bash_env-localbuild-1554130930
  CIRCLE_WORKING_DIRECTORY=~/project

====>> Checkout code
  #!/bin/bash -eo pipefail
mkdir -p /root/project && cd /tmp/_circleci_local_build_repo && git ls-files -z | xargs -0 tar -c | tar -x -C /root/project && cp -a /tmp/_circleci_local_build_repo/.git /root/project
/bin/bash: git: command not found
tar: Cowardly refusing to create an empty archive
Try `tar --help' or `tar --usage' for more information.
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
Error: Exited with code 2
Step failed
Error: runner failed (exited with 101)
Task failed
Error: task failed```

git is installed and available on my path.

**Comment by maarten-k** [comment] 2019-04-02 09:35
I reproduced also the same circleci error under Linux. Should this issue not move to bioconda-utils?

**Comment by marcusjwhelan** [comment] 2019-04-10 18:27
I am not using this package just CircleCI and I get this exact same error. I have seen people say its something to do with the url being https and not ssh format.

**Comment by skurscheid** [comment] 2019-04-16 03:04
@marcusjwhelan 
> I am not using this package just CircleCI and I get this exact same error. I have seen people say its something to do with the url being https and not ssh format.

I don't think that's the issue as I am using ssh in my repository URL - seems more like a PATH issue in the docker image/circelci script. But I am only scraping the surface of the whole process...

**Comment by epruesse** [comment] 2019-04-17 21:21
Can you guys double check if this is current?

I think this is just an outdated docker image. `circleci build` seems to not check that it's the most current `latest` image, and we must have had some that were simply missing the `git` binary. The `latest` tag doesn't point to a specific build, but to the most recent image, and as much as it pains to admit it, those have been broken occasionally in the past.

Steps to debug:
```
docker pull bioconda/bioconda-utils-build-env:latest
circleci build
```

If it still doesn't work, have a look into the container:
```
$ docker run -it bioconda/bioconda-utils-build-env bash
root@fae70a24faba /]# which git
/opt/conda/bin/git
```

**Comment by maarten-k** [comment] 2019-04-18 06:53
@epruesse  The error still happens.  I did pull the docker container on semi-daily last 2 weeks and happened every time. Also in a fresh spin in an ubuntu 18.04 VM did not solve the problem (followed https://bioconda.github.io/contributing.html) 

>~/git/bioconda-recipes$ docker pull bioconda/bioconda-utils-build-env:latest
latest: Pulling from bioconda/bioconda-utils-build-env
Digest: sha256:359113e96c2c6b85583c04c0b4f0b084019677ba2a1c9d48bc15e467ba2f9964
Status: Image is up to date for bioconda/bioconda-utils-build-env:latest
~/git/bioconda-recipes$ circleci build
Docker image digest: sha256:6331ae078d92837f2513d5aca3f6344189531ab1bdf79bd7231392c7a4b0aa45
====>> Spin up Environment
Build-agent version 1.0.10191-59d6c584 (2019-04-04T09:13:55+0000)
Docker Engine Version: 18.06.1-ce
Kernel Version: Linux f4ca53be8a97 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 Linux
Starting container bioconda/bioconda-utils-build-env
  using image bioconda/bioconda-utils-build-env@sha256:359113e96c2c6b85583c04c0b4f0b084019677ba2a1c9d48bc15e467ba2f9964

>Using build environment variables
  BASH_ENV=/tmp/.bash_env-localbuild-1555569554
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=master
  CIRCLE_BUILD_NUM=
  CIRCLE_JOB=build
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_REPOSITORY_URL=git@github.com:bioconda/bioconda-recipes.git
  CIRCLE_SHA1=6dd21a6bb313773e77c4f0e13ece562669e69cad
  CIRCLE_SHELL_ENV=/tmp/.bash_env-localbuild-1555569554
  CIRCLE_WORKING_DIRECTORY=~/project

>====>> Checkout code
  #!/bin/bash -eo pipefail
mkdir -p /root/project && cd /tmp/_circleci_local_build_repo && git ls-files -z | xargs -0 tar -c | tar -x -C /root/project && cp -a /tmp/_circleci_local_build_repo/.git /root/project
/bin/bash: git: command not found
tar: Cowardly refusing to create an empty archive
Try `tar --help' or `tar --usage' for more information.
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
Error: Exited with code 2
Step failed
Error: runner failed (exited with 101)
Task failed
Error: task failed
~/git/bioconda-recipes$ docker run -it bioconda/bioconda-utils-build-env bash
[root@4dc8b730e235 /]# which git
/opt/conda/bin/git

>~/git/bioconda-recipes$ circleci version
0.1.5546+1fae6c8

**Comment by epruesse** [comment] 2019-04-18 15:45
Closing in favor of  https://github.com/bioconda/bioconda-utils/issues/503 and https://github.com/bioconda/bioconda-utils/issues/505

**Closed by epruesse** 2019-04-18 15:45 UTC
