### ISSUE TITLE
KMC does not include header files

### ISSUE THREAD

**Issue by yp** [bioconda/bioconda-recipes#32455] opened 2022-01-18 07:31 UTC
Since version 3.2.1, recipe for KMC does not include header files and libraries. Recipes that depends on those files will not build successfully.
See here: https://github.com/bioconda/bioconda-recipes/blob/4ce7298936a780610f3b9ccca0ae297a00cc132b/recipes/kmc/meta.yaml#L11

**Comment by yp** [comment] 2022-01-18 07:37
Is there any specific reason for that, @marekkokot?

**Comment by marekkokot** [comment] 2022-01-18 08:08
Hello,

honestly, I was not aware of that. Previously KMC recipe was prepared by someone else, but we felt like we should take care of this recipe to keep it up to date. I have decided to use statically precompiled binaries because from my experience it works best (I remember some issues that kmc from bioconda caused seg. faults). We use precompiled binaries on our GitHub releases and I wanted to keep bioconda recipe as close to our release as possible, yet I was not aware of libraries. It seems we need to reconsider how we publish KMC. My goal is to:
1. Keep GitHub releases as similar to bioconda recipe as possible
2. Don't break existing dependencies (those I mentioned)
3. Do not force users to install any compiler or bioconda, just download precompiled binaries

I am not sure if it is possible to keep all these requirements.

Out of curiosity, do you have any information on how many packages depend on these headers and libraries?
From what I see for previous KMC versions (3.1.1 for example) there is a libkmc.so for part of our code. It was not created originally by us. The problem is that in the current release we have also some library (libkmc_core.a). The problem is that those libraries are for completely different things, i.e. libkmc.so is for accessing kmc output files, while new libkmc_core.a allows integrating main kmc functionality in cpp code. From my perspective libkmc.so should be renamed to libkmc_api.so, but such rename will also break some packages I suppose. 

Do you have any recommendations?

**Comment by yp** [comment] 2022-01-19 13:39
Thanks for your response.
I don't know how many recipes rely on the library/headers that were available in the previous releases on bioconda but I'm contributing to one of them (https://github.com/bioconda/bioconda-recipes/tree/master/recipes/malva) that it will fail at the next build.
Is it maybe possible to replicate the build process that you use for GitHub release and adding `.so` and `.h*` files? Or maybe preparing a second recipe (something like `kmc-dev`) that includes those files?

I think that accessing kmc output files is a pretty important use case.

**Comment by marekkokot** [comment] 2022-01-24 06:42
Hi,
let me know if the new KMC build works as expected.

**Comment by yp** [comment] 2022-01-24 08:57
The new build works perfectly. Thanks!

**Comment by marekkokot** [comment] 2022-01-24 09:27
Great, thanks! I am not able to close the issue, could you close it?

**Closed** 2022-01-24 09:28 UTC
