### ISSUE TITLE
Installation of primer3-py via bioconda on Python 3.8, 3.9, and 3.10

### ISSUE THREAD

**Issue by akikuno** [bioconda/bioconda-recipes#44886] opened 2023-12-19 04:58 UTC
@bgruening 

Regarding the installation of primer3-py via Conda, it seems that only Python 3.11 is currently provided with the latest version (2.0.1).
https://anaconda.org/bioconda/primer3-py/files

My personal project uses pysam, and currently Python 3.8, 3.9, and 3.10 are supported for installation via conda.

Therefore, it would be greatly helpful if primer3-py could also be made available for Python 3.8, 3.9, and 3.10. (Any version is fine for me.)

Here's the recipe: https://github.com/bioconda/bioconda-recipes/tree/master/recipes/primer3-py

I would greatly appreciate your supports with this issue.

**Comment by corneliusroemer** [comment] 2023-12-20 20:57
Duplicate of:
- https://github.com/bioconda/bioconda-recipes/issues/37805

**Comment by corneliusroemer** [comment] 2023-12-20 23:30
I was wrong above, this isn't about lack of Python 3.11 support but the opposite: request to check why things don't work for 3.8-3.10, see 
- https://github.com/libnano/primer3-py/issues/127

**Closed** 2023-12-21 00:58 UTC
