### ISSUE TITLE
problem running HTSeq

### ISSUE THREAD

**Issue by dkoppstein** [bioconda/bioconda-recipes#2238] opened 2016-08-29 22:37 UTC
Am getting: 

```
Traceback (most recent call last):
  File "/efs/home/dkoppstein/analysis/rnaseq/cc_rnaseq_trial/env/conda2/bin/htseq-count", line 4, in <module>
    __import__('pkg_resources').run_script('HTSeq===0.6.1p1', 'htseq-count')
  File "/efs/home/dkoppstein/analysis/rnaseq/cc_rnaseq_trial/env/conda2/lib/python2.7/site-packages/pkg_resources.py", line 2655, in <module>
    working_set.require(__requires__)
  File "/efs/home/dkoppstein/analysis/rnaseq/cc_rnaseq_trial/env/conda2/lib/python2.7/site-packages/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/efs/home/dkoppstein/analysis/rnaseq/cc_rnaseq_trial/env/conda2/lib/python2.7/site-packages/pkg_resources.py", line 518, in resolve
    requirements = list(requirements)[::-1]  # set up the stack
  File "/efs/home/dkoppstein/analysis/rnaseq/cc_rnaseq_trial/env/conda2/lib/python2.7/site-packages/pkg_resources.py", line 2456, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/efs/home/dkoppstein/analysis/rnaseq/cc_rnaseq_trial/env/conda2/lib/python2.7/site-packages/pkg_resources.py", line 2424, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'HTSeq===0.6.1p1', 'at', '===0.6.1p1')
```

Looks like a typo in the htseq-count script, but oddly is specific to the bioconda tarballed bz2. It looks like I'm defaulting to this version: 

https://conda.anaconda.org/bioconda/linux-64/htseq-0.6.1.post1-py27_0.tar.bz2

Indeed, the typo is present in the script in the bzipped tarball. However, if I download the tarball from PyPI and install manually into the same environment using `python setup.py install`, the error is fixed. Maybe we should rebuild HTSeq? 

P.S. not sure how it passed tests...

**Comment by daler** [comment] 2016-08-30 13:51
Actually I can't reproduce:

```bash
conda create -n test-env python=2 htseq
source activate test-env
htseq-count
# ...
# 
# Written by Simon Anders (sanders@fs.tum.de), European Molecular Biology
# Laboratory (EMBL). (c) 2010. Released under the terms of the GNU General
# Public License v3. Part of the 'HTSeq' framework, version 0.6.1p1.
```

And building the recipe with tests, `CONDA_PY="2.7" conda build recipes/htseq`, works fine. Are you installing into an existing env? Maybe try bumping the build number to upload a new build and see if that fixes things?

**Comment by dkoppstein** [comment] 2016-08-30 20:14
Hmmm, interesting. I am indeed installing into an existing environment, and building a new environment from scratch works for me as well. Perhaps there is something in the environment that is causing this error. I'll try narrowing down what that might be.

**Comment by blaiseli** [comment] 2016-09-23 08:02
I think I had similar weird problems when the python with which a package was installed was not the same as the python with which it was run.

**Comment by bgruening** [comment] 2016-10-09 11:23
I will close this now. Please feel free to reopen if this is still a problem.

**Closed by bgruening** 2016-10-09 11:23 UTC
