### ISSUE TITLE
CircleCI/gcc issue on fresh Ubuntu

### ISSUE THREAD

**Issue by AlexanderDilthey** [bioconda/bioconda-recipes#12909] opened 2019-01-04 11:49 UTC
'circleci build' throws error messages about a nonfunctional C compiler, running under Ubuntu. This happens in the context of a replicated samtools recipe, which I thought would be a good place to get started.

To be specific, I followed the instructions under "Contributing a recipe". From a fresh fork, I created a `samtools2` folder, into which I copied `build.sh` and `meta.yml` from the original `samtools` folder. I also modified `package:name` and `extra:identifiers` in the new 'samtools2' folder.

`circleci build` then complains about issues with gcc:

```
...
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/opt/conda/conda-bld/samtools2_1546601938765/work':
...
```

Any advice?

This issue might be related to [another issue](https://github.com/bioconda/bioconda-recipes/issues/12773)

**Comment by gkarthik** [comment] 2019-01-04 23:52
I had a similar same issue here #12755

**Comment by bgruening** [comment] 2019-01-05 12:57
Duplicate of https://github.com/bioconda/bioconda-recipes/issues/12755

**Closed by bgruening** 2019-01-05 12:57 UTC
