### ISSUE TITLE
bioconductor-genomeinfodbdata offline conda failure

### ISSUE THREAD

**Issue by Netzach** [bioconda/bioconda-recipes#11485] opened 2018-10-22 21:58 UTC
I have a local offline mirror of bioconda for a secure data research cluster. One of the prereqs for a popular package is bioconductor-genomeinfodbdata, but that can’t be installed offline, since it just contains hardcoded URLs instead of actually providing the package, which screws up a lot of functions in conda. Could this be changed in any way? (The file in question is only 17.1 MB)

**Comment by dpryan79** [comment] 2018-11-01 15:04
You'll need to copy that file in yourself then. The various bioconductor data packages were changed in this way to save some space.

**Comment by krinsman** [comment] 2018-12-05 22:42
I am also having issues with bioconductor-genomeinfodbdata, since even when online `library("GenomeInfoDbData")` fails with 
```
Error in library("GenomeInfoDbData"): there is no package called ‘GenomeInfoDbData’
```
even after installing bioconductor-genomeinfodbdata. I am not sure whether this is actually related to your issue though, so I apologize for the unintentional thread hijacking if this is unrelated.

Anyway it GenomeInfoDbData doesn't show up in my R library, even though GenomeInfoDb does.

**Comment by dpryan79** [comment] 2018-12-05 23:14
I just tried the following with success:

    $ conda create -n genomeinfodb bioconductor-genomeinfodb bioconductor-genomeinfodbdata
    $ source activate genomeinfodb
    $ R
    > .libPaths(R.home("library"))  # This causes R to ignore non-conda packages
    > library(GenomeInfoDbData)
    > data(specData)  # This is what the package actually contains
    > head(specData)

The last command returned:

      tax_id        genus               species
    1      1          all                  <NA>
    2      1         root                  <NA>
    3      2     Bacteria                  <NA>
    4      2          not Bacteria Haeckel 1894
    5      6 Azorhizobium                  <NA>
    6      7 Azorhizobium           caulinodans

I can't reproduce any issues with the package when online.

**Comment by dpryan79** [comment] 2019-03-28 08:35
Closing for now, if this reoccurs then please feel free to reopen.

**Closed** 2019-03-28 08:34 UTC

**Comment by bobermayer** [comment] 2025-09-10 14:09
in our case, this is caused by problems with newer versions of openssl. it works with openssl < 3.5.0 (e.g., 3.4.1) and by forcing conda to stick with that (`--freeze-installed`)
