### ISSUE TITLE
python-dateutil removed: when/why/how?

### ISSUE THREAD

**Issue by mbargull** [bioconda/bioconda-recipes#9161] opened 2018-06-06 07:59 UTC
Related Gitter conversation:

----
@epruesse https://gitter.im/bioconda/Lobby?at=5b0f3352b8abab25d37eac02
>Was the `python-dateutil` package recently moved to `bioconda-legacy`?
Just ran into a problem where an archived conda environment (snakemake style, just URLs in the file) broke because the URL for python-dateutil returns a 404 now.
That's sort of a problem ... breaks reproducibility. 

@mbargull https://gitter.im/bioconda/Lobby?at=5b11349db6eece791dcea518
>@epruesse, it looks like `python-dateutil 2,3` is in `bioconda-legacy` since a long time. But I guess you are more concerned about `python-dateutil 2.6`: apparently that one was available in `bioconda` at some point (at least judging by the build/commit logs) but has been removed completely. That's indeed not a good thing. I can only speculate that before the practice to just label packages as `broken` or `deprecated` (=moved to `conda-forge`, usually) was adopted, that some packages were outright removed from the channel. It's definitely horribly regarding reproducibility, but I assume such things only affected a few packages and shouldn't/won't be done in future.

@epruesse https://gitter.im/bioconda/Lobby?at=5b1574497cb6a231358bcfee
>@mbargull Curiously, I was getting the `2.3` until like a week or two ago. Don't know how, but I've got the resolved packages in a git and it's definitely not been months.
W.r.t. reproducibility, it might just be necessary to point out somewhere that packages may move to bioconda-legacy, so resolved environmets with fully specified versions should add that to the channel list.

@mbargull https://gitter.im/bioconda/Lobby?at=5b1792a1352b9e1a4b62002f
>@epruesse
>>Curiously, I was getting the 2.3 until like a week or two ago. Don't know how, but I've got the resolved packages in a git and it's definitely not been months.
>
>That's really odd and I'm curious what happened there, too => I'll open up an issue

----
Looking at the "Updated" dates on https://anaconda.org/bioconda-legacy/repo, it looks like `python-dateutil` has been a while on `bioconda-legacy`. But those dates, of course, give no indication on when the package was removed from `bioconda`. @bioconda/core: Has the package been removed recently?

Also, `bioconda-legacy` predates my involved so I don't know about its overall use. Don't we just move packages to other labels (`broken`, `deprecated`, `in-conda-forge`) instead of to other channels now? And I think we generally\* should not delete packages, right?!
(\* apart from license infringements and such, of course)

**Comment by daler** [comment] 2018-06-06 15:05
@mbargull @epruesse a security log does exist on the bioconda account, so the information is there. It's a matter of figuring out how to actually access it without clicking hundreds of times.

I don't think we have a solid policy on where deprecated/duplicated/broken packages should go. This needs to be clearly documented, and we need a section in the docs for users who are hitting this sort of issue. We currently have a mix of labels and channels, I think 

```
--channel bioconda/labels/broken \
--channel bioconda/labels/duplicate \
--channel bioconda/labels/in-conda-forge \
--channel bioconda/labels/deprecated \
--channel bioconda-legacy
```

would catch everything. But that's messy.

For a while I've been meaning to get a TSV approach to list which packages are moved where, and importantly adding metadata like *why* and *when*. Time to revisit that, I think.

**Comment by daler** [comment] 2018-06-06 18:12
Following up: thanks to the kind folks at Anaconda Cloud I got a JSON dump of the event log. Looks like python-dateutil=2.6.0 was removed from the main channel almost a year ago exactly, but 2.3 doesn't have a record of being removed. Not quite sure what happened there.

The relevant pieces of the log are:

<details>

```
time                              basename                                       action               package_name     basename
2017-06-07T14:03:43.277000+00:00  osx-64/python-dateutil-2.6.0-py36_0.tar.bz2    package.file.remove  python-dateutil  osx-64/python-dateutil-2.6.0-py36_0.tar.bz2
2017-06-07T14:03:43.166000+00:00  osx-64/python-dateutil-2.6.0-py27_0.tar.bz2    package.file.remove  python-dateutil  osx-64/python-dateutil-2.6.0-py27_0.tar.bz2
2017-06-07T14:03:43.055000+00:00  linux-64/python-dateutil-2.6.0-py35_0.tar.bz2  package.file.remove  python-dateutil  linux-64/python-dateutil-2.6.0-py35_0.tar.bz2
2017-06-07T14:03:42.947000+00:00  linux-64/python-dateutil-2.6.0-py27_0.tar.bz2  package.file.remove  python-dateutil  linux-64/python-dateutil-2.6.0-py27_0.tar.bz2
2017-06-07T14:03:42.842000+00:00  linux-64/python-dateutil-2.6.0-py34_0.tar.bz2  package.file.remove  python-dateutil  linux-64/python-dateutil-2.6.0-py34_0.tar.bz2
2017-06-07T14:03:42.735000+00:00  osx-64/python-dateutil-2.6.0-py34_0.tar.bz2    package.file.remove  python-dateutil  osx-64/python-dateutil-2.6.0-py34_0.tar.bz2
2017-06-07T14:03:42.629000+00:00  linux-64/python-dateutil-2.6.0-py36_0.tar.bz2  package.file.remove  python-dateutil  linux-64/python-dateutil-2.6.0-py36_0.tar.bz2
2017-06-07T14:03:42.525000+00:00  osx-64/python-dateutil-2.6.0-py35_0.tar.bz2    package.file.remove  python-dateutil  osx-64/python-dateutil-2.6.0-py35_0.tar.bz2
2017-05-09T16:34:39.240000+00:00  osx-64/python-dateutil-2.6.0-py36_0.tar.bz2    package.file.upload  python-dateutil  osx-64/python-dateutil-2.6.0-py36_0.tar.bz2
2017-05-05T22:08:47.618000+00:00  linux-64/python-dateutil-2.6.0-py36_0.tar.bz2  package.file.upload  python-dateutil  linux-64/python-dateutil-2.6.0-py36_0.tar.bz2
2017-02-28T06:49:24.706000+00:00  osx-64/python-dateutil-2.6.0-py34_0.tar.bz2    package.file.upload  python-dateutil  osx-64/python-dateutil-2.6.0-py34_0.tar.bz2
2017-02-28T06:49:22.671000+00:00  osx-64/python-dateutil-2.6.0-py27_0.tar.bz2    package.file.upload  python-dateutil  osx-64/python-dateutil-2.6.0-py27_0.tar.bz2
2017-02-28T06:49:20.738000+00:00  osx-64/python-dateutil-2.6.0-py35_0.tar.bz2    package.file.upload  python-dateutil  osx-64/python-dateutil-2.6.0-py35_0.tar.bz2
2017-02-28T06:41:04.417000+00:00  linux-64/python-dateutil-2.6.0-py35_0.tar.bz2  package.file.upload  python-dateutil  linux-64/python-dateutil-2.6.0-py35_0.tar.bz2
2017-02-28T06:41:02.723000+00:00  linux-64/python-dateutil-2.6.0-py27_0.tar.bz2  package.file.upload  python-dateutil  linux-64/python-dateutil-2.6.0-py27_0.tar.bz2
2017-02-28T06:41:00.979000+00:00  linux-64/python-dateutil-2.6.0-py34_0.tar.bz2  package.file.upload  python-dateutil  linux-64/python-dateutil-2.6.0-py34_0.tar.bz2
2017-02-28T06:40:59.964000+00:00                                                 release.create       python-dateutil
2016-01-06T17:16:51.404000+00:00  linux-64/python-dateutil-2.3-py27_0.tar.bz2    package.file.upload  python-dateutil  linux-64/python-dateutil-2.3-py27_0.tar.bz2
2016-01-06T17:16:51.367000+00:00  linux-64/python-dateutil-2.3-py27_0.tar.bz2    package.file.upload  python-dateutil  linux-64/python-dateutil-2.3-py27_0.tar.bz2
2016-01-06T17:16:49.578000+00:00  linux-64/python-dateutil-2.3-py34_0.tar.bz2    package.file.upload  python-dateutil  linux-64/python-dateutil-2.3-py34_0.tar.bz2
2016-01-06T17:16:49.531000+00:00  linux-64/python-dateutil-2.3-py34_0.tar.bz2    package.file.upload  python-dateutil  linux-64/python-dateutil-2.3-py34_0.tar.bz2
2016-01-06T17:16:47.346000+00:00  linux-64/python-dateutil-2.3-py35_0.tar.bz2    package.file.upload  python-dateutil  linux-64/python-dateutil-2.3-py35_0.tar.bz2
2016-01-06T17:16:47.306000+00:00  linux-64/python-dateutil-2.3-py35_0.tar.bz2    package.file.upload  python-dateutil  linux-64/python-dateutil-2.3-py35_0.tar.bz2
2016-01-06T17:10:04.146000+00:00  osx-64/python-dateutil-2.3-py27_0.tar.bz2      package.file.upload  python-dateutil  osx-64/python-dateutil-2.3-py27_0.tar.bz2
2016-01-06T17:10:04.105000+00:00  osx-64/python-dateutil-2.3-py27_0.tar.bz2      package.file.upload  python-dateutil  osx-64/python-dateutil-2.3-py27_0.tar.bz2
2016-01-06T17:10:02.353000+00:00  osx-64/python-dateutil-2.3-py35_0.tar.bz2      package.file.upload  python-dateutil  osx-64/python-dateutil-2.3-py35_0.tar.bz2
2016-01-06T17:10:02.314000+00:00  osx-64/python-dateutil-2.3-py35_0.tar.bz2      package.file.upload  python-dateutil  osx-64/python-dateutil-2.3-py35_0.tar.bz2
2016-01-06T17:10:00.678000+00:00  osx-64/python-dateutil-2.3-py34_0.tar.bz2      package.file.upload  python-dateutil  osx-64/python-dateutil-2.3-py34_0.tar.bz2
2016-01-06T17:10:00.641000+00:00  osx-64/python-dateutil-2.3-py34_0.tar.bz2      package.file.upload  python-dateutil  osx-64/python-dateutil-2.3-py34_0.tar.bz2
2016-01-06T17:09:59.133000+00:00                                                 release.create       python-dateutil
2016-01-06T17:09:59.027000+00:00                                                 package.create       python-dateutil
```

</details>

**Comment by PertuyF** [comment] 2018-06-19 15:23
I confirm that I was also resolving the install of `python-dateutil==2.3=py35_0` with `bioconda` channel only a few weeks ago.
It works with specifying `bioconda-legacy` right now, but I never had to use this one before.

I saw some recipes removed from `bioconda` last week (doublons with conda-forge if I remember well), could it be a side-effect?

**Comment by epruesse** [comment] 2018-06-19 15:47
Does `conda` have any built-in mechanism for dealing with legacy/deprecated packages allowing to at the same time excluding a package from "naive" installations but keeping it available for reproducing archived environments?

At the very least, we should document the `bioconda-legacy` approach wherever we describe the reproducibility.

For myself, I've added a mechanism to my environment-installer to try alternate URLs for packages from archived environments (i.e. on 404 it tries rewriting bioconda to bioconda-legacy, which fixed the dateutil issue for me).

**Comment by bgruening** [comment] 2019-09-30 14:35
We are using now labels to archive the same effect so I think this can be closed.

**Closed by bgruening** 2019-09-30 14:35 UTC
