### ISSUE TITLE
Problem when enabling circleci on a fork

### ISSUE THREAD

**Issue by abretaud** [bioconda/bioconda-recipes#8235] opened 2018-03-12 16:35 UTC
Hi,
A little problem we encountered while working on #8203 with @rizkg: as [written in the doc](https://bioconda.github.io/contribute-a-recipe.html#push-changes-wait-for-tests-to-pass-submit-pull-request) he enabled circleci on his fork, but the result is that when he creates his PR, the tests are only run on https://circleci.com/gh/rizkg/bioconda-recipes/ instead of https://circleci.com/gh/bioconda/bioconda-recipes/.
So he gets a `Sorry! Your build didn't run because it looks like you haven't selected an macOS plan yet` error for macos builds. Pushing new commits to his PR doesn't fix the problem.

To make it work he disabled circleci build on his fork and pushed a new commit to his PR.

Should we discourage enabling circleci on forks, or is there some magic circleci option to workaround this?

**Comment by bgruening** [comment] 2018-03-12 16:43
I invited @rizkg to bioconda. Please cancel your private plan with circle-CI ... then it should work. Sorry, this is really messy :(

**Comment by abretaud** [comment] 2018-03-12 16:52
No problem, i can make a PR for the doc if that's the way to go (nothing urgent for me)

**Comment by apeltzer** [comment] 2018-03-13 09:56
Same happened to me in #8209 - could you invite me too @bgruening? I'll work on adding a couple of new recipes in the next days and will anyways just submit as pull requests....

**Comment by wdecoster** [comment] 2018-03-13 13:29
Same issue in https://github.com/bioconda/bioconda-recipes/pull/8134

**Comment by daler** [comment] 2018-03-21 15:24
Turns out the problem is actually independent of being a bioconda team member -- it's just due to having CircleCI enabled on the fork. Addressed in https://github.com/bioconda/bioconda-utils/pull/286, where we're no longer recommending enabling CircleCI for a fork (and in fact explicitly asking to disable it for the fork).

Sorry for the confusion!

**Closed by daler** 2018-03-21 15:24 UTC
