### ISSUE TITLE
Create recipe for medaka 1.12.0 please

### ISSUE THREAD

**Issue by ZarulHanifah** [bioconda/bioconda-recipes#48855] opened 2024-07-01 17:18 UTC
["Oxford Nanopore Technologies does not supply or support the bioconda distribution of medaka. Please raise this issue on the bioconda issues page."](https://github.com/nanoporetech/medaka/issues/513)

Idk why wouldnt ONT put their own software on bioconda for easy distribution. Anyways, please help me! The pip link is here:
[https://pypi.org/project/medaka/](https://pypi.org/project/medaka/)

**Comment by aliciaaevans** [comment] 2024-07-01 21:58
I'm rebuilding https://github.com/bioconda/bioconda-recipes/pull/48523 to see what errors might be keeping the update from being merged.

**Comment by martin-g** [comment] 2024-07-02 08:07
The problem is here - https://github.com/bioconda/bioconda-recipes/blob/d9a796700d865402b03bccf5b2081f22b35eb1ef/recipes/medaka/conda_build_config.yaml
Medaka uses tensorflow 2.10 (https://github.com/nanoporetech/medaka/blob/0cc6f51c96f47eaf8f2135c3082980d0e7f75494/requirements.txt#L8) that needs OpenSSL 1.1.1 but Medaka itself needs OpenSSL 3.x
The "fix" is easy - https://github.com/bioconda/bioconda-recipes/pull/46801/files#diff-c4e50da4c5af49617da084e58a8fe2bd721475988e0cd0b8c8ffa4900c430be8. But I am not sure whether it will cause problems at runtime later.

**Comment by martin-g** [comment] 2024-07-02 11:10
```
09:23:21 BIOCONDA INFO (OUT) Encountered problems while solving:
09:23:21 BIOCONDA INFO (OUT)   - package htslib-1.14-h9093b5e_0 requires libcurl >=7.79.1,<8.0a0, but none of the providers can be installed
09:23:21 BIOCONDA INFO (OUT) 
09:23:21 BIOCONDA INFO (OUT) Could not solve for environment specs
09:23:21 BIOCONDA INFO (OUT) The following packages are incompatible
09:23:21 BIOCONDA INFO (OUT) ├─ htslib >=1.14  is installable with the potential options
09:23:21 BIOCONDA INFO (OUT) │  ├─ htslib [1.14|1.15] would require
09:23:21 BIOCONDA INFO (OUT) │  │  └─ libcurl >=7.81.0,<8.0a0 , which can be installed;
09:23:21 BIOCONDA INFO (OUT) │  ├─ htslib 1.14 would require
09:23:21 BIOCONDA INFO (OUT) │  │  └─ libcurl >=7.79.1,<8.0a0 , which can be installed;
09:23:21 BIOCONDA INFO (OUT) │  ├─ htslib [1.15.1|1.16] would require
09:23:21 BIOCONDA INFO (OUT) │  │  └─ libcurl >=7.83.1,<8.0a0 , which can be installed;
09:23:21 BIOCONDA INFO (OUT) │  ├─ htslib 1.15.1 would require
09:23:21 BIOCONDA INFO (OUT) │  └─ libcurl 8.8.0, which can be installed (as previously explained);
09:23:21 BIOCONDA INFO (OUT) └─ openssl 1.1.1.*  is not installable because it conflicts with any installable versions previously reported.
09:23:28 BIOCONDA ERROR COMMAND FAILED (exited with 1): docker run -t --net host --rm -v /tmp/tmp2f3wwsrm/build_script.bash:/opt/build_script.bash -v /opt/mambaforge/envs/bioconda/conda-bld:/opt/host-conda-bld -v /home/vsts/work/1/s/recipes/medaka:/opt/recipe -e LANG=C.UTF-8 -e HOST_USER_ID=1001 quay.io/bioconda/bioconda-utils-build-env-cos7:3.3.1 /bin/bash /opt/build_script.bash
```

**Comment by ZarulHanifah** [comment] 2024-07-02 13:27
I can try runtime and see if it works

**Closed** 2024-09-17 05:32 UTC
