### ISSUE TITLE
ncurses linking error on Arch

### ISSUE THREAD

**Issue by yhoogstrate** [bioconda/bioconda-recipes#2387] opened 2016-09-24 07:29 UTC
Hello everyone,

I am experiencing an issue with tools linked with ncurses (samtools and tmux). It terminates with the following error:
```
tmux: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
```
and so does samtools.

Similarly, ldd indicates it's not present:
```
ldd $(which tmux)    
	linux-vdso.so.1 (0x00007fff724b2000)
	libutil.so.1 => /usr/lib/libutil.so.1 (0x00007f5c12e85000)
	libncurses.so.5 => not found
	libevent-2.0.so.5 => /home/youri/miniconda2/envs/tmux/bin/../lib/libevent-2.0.so.5 (0x00007f5c12c42000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f5c12a3a000)
	libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f5c12823000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f5c12485000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f5c12268000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f5c13088000)
```
This also seems to be correct:
```
ll /home/youri/miniconda2/envs/tmux/lib | grep curse
   0 lrwxrwxrwx 1 youri youri   13 Sep 24 09:16 libncurses.a -> libncursesw.a
   0 lrwxrwxrwx 1 youri youri   15 Sep 24 09:16 libncurses++.a -> libncurses++w.a
   0 lrwxrwxrwx 1 youri youri   18 Sep 24 09:16 libncurses.so -> libncursesw.so.5.9
168K -rw-r--r-- 7 youri youri 167K Jul 13 15:29 libncurses++w.a
812K -rw-r--r-- 7 youri youri 810K Jul 13 15:29 libncursesw.a
   0 lrwxrwxrwx 1 youri youri   18 Sep 24 09:16 libncursesw.so -> libncursesw.so.5.9
   0 lrwxrwxrwx 1 youri youri   18 Sep 24 09:16 libncursesw.so.5 -> libncursesw.so.5.9
464K -rwxrwxr-x 1 youri youri 463K Sep 24 09:16 libncursesw.so.5.9
```
If I understand this correctly it looks like somehow the build process made use of `libncurses.so.5` which does not seem to exist in the ncurses available in the R channel.

As workaround I make for every environment a symlink to the .so file. Does anybody have an idea how to fix this?

**Comment by bgruening** [comment] 2016-09-24 08:10
This is fixed in a ncurses version of conda-forge. Can you enable conda-forge before the r-channel and test? We are pretty close to enable conda-forge and all this will go away.
The root cause was probably that back in time we build this package out build-environment container ncureses and many other libs, this has also changed recently. So we getting better and better :)

**Comment by yhoogstrate** [comment] 2016-09-24 11:42
Thanks @bg, adding conda-forge solved this properly, thanks you deserve a medal!

"*...this has also changed recently.*" Meaning that rebuilding by only increasing the build version would also solve it?

**Comment by bgruening** [comment] 2016-09-24 11:46
I haven't tried but I think a rebuilt will solve it as well.

**Closed** 2016-09-24 11:57 UTC

**Comment by yhoogstrate** [comment] 2016-09-24 12:19
Yes, it solved it. The proper binary is now available in bioconda and does not require conda-forge.

**Comment by bgruening** [comment] 2016-09-24 12:44
Awesome! Thanks.
