### ISSUE TITLE
simulate-travis.py

### ISSUE THREAD

**Issue by roryk** [bioconda/bioconda-recipes#7419] opened 2018-01-29 20:38 UTC
Where did it go?

**Comment by roryk** [comment] 2018-01-29 20:45
Oh I see, swapped over to a new CI system.

**Comment by philres** [comment] 2018-01-29 21:17
Sorry for hijacking your thread, but I'm having the same problem. How did you solve it?

I cloned the repo but it does not have the `simulate-travis.py`

Thanks,
Philipp

**Comment by roryk** [comment] 2018-01-29 21:26
Heya, I just ignored the local testing for now since the documentation isn't updated for the new CI. So I pushed to a forked repository, opened a pull request and let the CI handle the testing rather than doing it locally.

**Comment by mbargull** [comment] 2018-01-29 21:57
duplicate of https://github.com/bioconda/bioconda-recipes/issues/7375.

**Closed by mbargull** 2018-01-29 21:57 UTC
