### ISSUE TITLE
Roary recipe stuck on solving environment when conda-forge is included (required)

### ISSUE THREAD

**Issue by elsherbini** [bioconda/bioconda-recipes#10102] opened 2018-07-26 18:26 UTC
I am trying to install [roary from bioconda](https://anaconda.org/bioconda/roary).

When I install without conda-forge, it says that packages are not found (though I do see all of them except for libgd available)

Then, when I add conda-forge, it gets stuck at the solving environment stage.
```
[josephe@eofe4 roary]$ conda create --name=roary -c bioconda roary
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - roary
  - perl-bioperl-core[version='<1.7']
  - perl-bio-featureio
  - roary
  - perl-bioperl-core[version='<1.7']
  - perl=5.22.0
  - roary
  - perl-bioperl-core[version='<1.7']
  - perl-bio-samtools
  - roary
  - perl-bioperl-core[version='<1.7']
  - perl-gd
  - libgd[version='>=2.2.3']
  - roary
  - perl-bioperl-core[version='<1.7']
  - perl-bio-phylo
  - roary
  - perl-bioperl-core[version='<1.7']
  - perl-bio-asn1-entrezgene

Current channels:

  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-64
  - https://repo.anaconda.com/pkgs/free/noarch

```
```
[josephe@eofe4 roary]$ conda create --name=roary -c bioconda -c conda-forge roary

<STUCK on Solving environment forever>

```

**Comment by rvalieris** [comment] 2018-07-30 18:34
I left it running, and it took about 3 hours to finish on my machine, this looks like a conda issue, it would be better to open a issue [there](https://github.com/conda/conda/).

also, it looks like you can bypass the problem by asking it to install `roary=3.12.0`

all this is using the conda-forge channel, there are many packages there that bioconda packages depend on, you will not be able to install it otherwise.

**Comment by druvus** [comment] 2018-09-19 11:06
@elsherbini Roary was rebuilt in #11017 so could you test if it is working now?

**Comment by druvus** [comment] 2019-05-02 10:43
Confirmed it is now working so closing.

**Closed by druvus** 2019-05-02 10:43 UTC
