### ISSUE TITLE
Repeatmodeler package not working

### ISSUE THREAD

**Issue by helltish** [bioconda/bioconda-recipes#9988] opened 2018-07-19 14:02 UTC
Dear developer Team,

we have compared the bioconda Repeatmodeler package with a local installation of Repeatmodeler (with all dependencies).

The local installation of Repeatmodeler produced an output, which is reasonable for our input file. The conda package does not produce any output. Please find our logs to compare. The input data was the same in both cases.

Thanks a lot in advance!

**Comment by helltish** [comment] 2018-07-19 14:09
[RepeatModeler_conda.log](https://github.com/bioconda/bioconda-recipes/files/2210248/RepeatModeler_conda.log)
[RepeatModeler_local_installation.log](https://github.com/bioconda/bioconda-recipes/files/2210249/RepeatModeler_local_installation.log)

**Comment by corburn** [comment] 2018-08-14 02:40
>NOTE: RepeatScout did not return any models.

**Comment by mbnmbn00** [comment] 2018-11-28 18:37
Exactly same issue here. Manually installed RepeatModeler worked well on the same assembly.
I also noticed that `nseg` which is needed for RepeatScout was not installed.
Manually compiling and locating at `bin` directory didn't help.

`<prefix>.fa.rscons.filtered` file which is one of RepeatScout outputs was empty, too. So I assume that RepeatScout has failed at some point.

**Comment by astulaaa** [comment] 2019-11-26 07:08
coda Repeatmodeler package still not working properly

**Comment by jebrosen** [comment] 2019-12-04 17:41
I believe the underlying issue is here:
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/repeatmodeler/build.sh#L23

The RepeatScout package in bioconda does not include `filter-stage-1.prl` in the `bin` directory, but that program is used by RepeatModeler.

**Comment by Juke34** [comment] 2019-12-04 22:08
I'm working on it with this PR #19088.  I guess it could work like it is in this PR (without nseg) but to be perfect it would be nice to include nseg. But there is currently no recipe for it. nseg is available here ftp://ftp.ncbi.nih.gov/pub/seg/nseg.

**Comment by Juke34** [comment] 2019-12-06 10:11
In the build3 of RepeatScout nseg and filter-stage-1.prl are now included, but the result seems still the same. How can we check manually which step is failing? Maybe one of this tool do not behaves like they should

**Comment by jebrosen** [comment] 2019-12-06 18:57
I believe at this point the remaining bug is in the `RepModelConfig.pm` and/or the `RepeatModeler` wrapper script shipped in bioconda: it sets `$TRF_PRGM = $ENV{'TRF_DIR'};` which is something like `.../conda/bin`, but `TRF_PRGM` is supposed to be the path to the `trf` binary itself (`.../conda/bin/trf`) - the same goes for `NSEG_PRGM`. Either `RepModelConfig.pm` or the wrapper should be modified to set the correct paths.

There could be other problems in the custom `RepModelConfig.pm` that I haven't noticed, but those two are directly causing this particular issue.

**Comment by Juke34** [comment] 2019-12-06 19:02
Thank you for your help, I succeeded to fix that today. Now this step is working fine. 
I have now a problem later in the execution:

```
 -- Refining Family R=207 / 0 ( RS Elements: 2212, Using 100 ):
RepeatModeler: Could not open refined model /scratch/jacda119/RM_19538.FriDec61556042019/round-1/family-0.fa.refiner_cons!
```

**Comment by jebrosen** [comment] 2019-12-06 21:42
@Juke34 Does that happen for every model or only some of them? I can try to reproduce that in a clean environment... probably next week.

**Comment by Juke34** [comment] 2019-12-06 21:58
I found! It is because the PATH to RepeatClassifier, Refiner and TRFMask are wrong. They are called directly in the RepeatModeler folder (in share), that cause an error e.g: 
'-bash: ./TRFMask: /u1/local/bin/perl: bad interpreter: No such file or directory'

while they have to be called as the other tools by the bin folder where there is a wrapper to call them  like that:
perl path/to/share/RepeatModeler/TRFMask options

But I'm getting close, I found a (nasty) way to fix the problem by modifying the code during installation with a sed command. I'm trying locally and it seems to work ... will see if I face up another problem

**Comment by jebrosen** [comment] 2019-12-06 22:06
`./TRFMask: /u1/local/bin/perl: bad interpreter: No such file or directory`

Yes... the `configure` script fixes all of those `perl` lines but bioconda does not use it. Hopefully with the newest version of RepeatModeler where `configure` supports command line arguments and does not need to be run interactively, bioconda can use `configure` instead.

**Comment by Juke34** [comment] 2019-12-07 17:46
It run until the end now. Except at the very end I have this message ```
Missing /home/jacda119/anaconda3/envs/repeatmodeler/share/RepeatMasker/Libraries/RepeatPeps.lib.psq!
Please rerun the configure program in the RepeatModeler directory
before running this script.
  - Looking for similarity to known repeat proteins..
Classification Time: 00:00:26 (hh:mm:ss) Elapsed Time
Program Time: 12:19:15 (hh:mm:ss) Elapsed Time
Working directory:  /scratch/jacda119/RM_33119.FriDec62053432019
may be deleted unless there were problems with the run.

The results have been saved to:
[...]
```
Is this RepeatPeps.lib.psq important? What it is use for? Can we skip this step? If we need this file how can we include it in the package? I don't know from where it is supposed to come

**Comment by jebrosen** [comment] 2019-12-07 18:12
I think that message is wrong - it should say to re-run `configure` in the RepeatMasker directory, which bioconda also does not do. This should only affect the classification step, but it's a pretty big part of it.

**Comment by Juke34** [comment] 2019-12-07 19:38
That means I need to fix the repeatmasker recipe too to create this file. Could you tell me the steps needed to create this file without using the configure? There is a file called RepeatPeps.lib so I guess there is one step to create the RepeatPeps.lib.psq from it.

**Comment by jebrosen** [comment] 2019-12-07 19:42
It used to be done by the package - https://github.com/bioconda/bioconda-recipes/blob/master/recipes/repeatmasker/build.sh#L21. Like RepeatModeler, the latest version of RepeatMasker has a `configure` script that can be run non-interactively so that should be easier in the future.

**Comment by Juke34** [comment] 2019-12-08 19:53
Actually is just a file made by makeblastdb command. No need to touch the RepeatMasker recipe for that, I can fix it directly from the RepeatModeler recipe then.

**Comment by Juke34** [comment] 2019-12-13 11:36
The recipe is now fixed in repeatmodeler-1.0.11 build **pl526_2**  (see #19137).

**Comment by Juke34** [comment] 2020-01-29 15:47
@helltish you can close the issue now.

**Comment by cement-head** [comment] 2020-09-21 14:29
Hello,

   I just got this bug

```
RepeatClassifier Version 2.0.1
======================================
Search Engine = rmblast
  - Looking for Simple and Low Complexity sequences..
  - Looking for similarity to known repeat proteins..
Missing /home/cbfgws6/Programs/rpmskr/RepeatMasker//Libraries/RepeatPeps.lib.psq!
Please rerun the configure program in the RepeatModeler directory
before running this script.
```

How exactly should I fix it?

**Comment by Juke34** [comment] 2020-09-21 20:18
What version did you use?

**Comment by mbnmbn00** [comment] 2020-09-21 20:32
Hello, I have the exact same issue.
What I had to do is run `./configure` again. I think configure includes downloading the database and make a blast database.

```
cd $(dirname $(which RepeatMasker))/../share/RepeatMasker
# ./configure downloads required databases
echo -e "\n2\n$(dirname $(which rmblastn))\n\n5\n" > tmp && ./configure < tmp
```

Hope it helps. (I'm using RepeatMasker 2.0.1)

repeatmasker              4.0.9_p2                pl526_2    bioconda
repeatmodeler             2.0.1                   pl526_0    bioconda
repeatscout               1.0.6                h516909a_1    bioconda

**Comment by Juke34** [comment] 2020-09-21 20:40
I checked repeatmasker  4.0.9_p2  and 4.1.0 and indeed the RepeatMaskerLib db in not set properly...
```
-rw-rw-r--  2 jacda119  wheel    18755326 Sep 15 21:14 RMRBMeta.embl
-rw-rw-r--  2 jacda119  wheel   113343436 Sep 15 21:14 taxonomy.dat
-rw-rw-r--  2 jacda119  wheel        5550 Sep 15 21:15 RepeatPeps.readme
-rw-rw-r--  2 jacda119  wheel    17979984 Sep 15 21:15 RepeatPeps.lib
-rwxrwxr-x  2 jacda119  wheel    22475384 Sep 15 21:15 RepeatAnnotationData.pm
-rw-rw-r--  2 jacda119  wheel         214 Sep 15 21:15 README.meta
-rw-rw-r--  2 jacda119  wheel  1869701327 Sep 15 21:15 Dfam.hmm
-rw-rw-r--  2 jacda119  wheel    24005361 Sep 15 21:15 Dfam.embl
-rwxrwxr-x  2 jacda119  wheel       25283 Sep 15 21:15 Artefacts.embl
-rw-rw-r--  2 jacda119  wheel    22661790 Sep 15 21:15 RepeatMaskerLib.embl
-rw-rw-r--  2 jacda119  wheel           0 Sep 15 21:15 RepeatMasker.lib
-rw-rw-r--  2 jacda119  wheel    16168295 Sep 15 21:15 RepeatPeps.lib.psq
-rw-rw-r--  2 jacda119  wheel     2931407 Sep 15 21:15 RepeatPeps.lib.phr
-rw-rw-r--  1 jacda119  wheel      144448 Sep 21 22:14 RepeatPeps.lib.pin
```

**Comment by Juke34** [comment] 2020-09-21 20:57
For RepeatMasker version 4.0.9_p2 the easiest would be to do 
`makeblastdb -dbtype nucl -in $CONDA_PREFIX/share/RepeatMasker/Libraries/RepeatMasker.lib`. This line should be added in the `build.sh` if we want to fix this version of the recipe.

For version 4.1.0 we use the following command:
`perl ./configure -libdir ${RM_DIR}/Libraries -trf_prgm ${PREFIX}/bin/trf  -rmblast_dir ${PREFIX}/bin/ -hmmer_dir ${PREFIX}/bin -abblast_dir ${PREFIX}/bin -crossmatch_dir ${PREFIX}/bin`
@jebrosen is there any reason why the RepeatMasker.lib db is not set properly with the configure? It

**Comment by jebrosen** [comment] 2020-09-21 22:44
The last few comments look like multiple issues that may or may not be related to each other. This is the current state of affairs for these files, to the best of my knowledge:

* `RepeatPeps.lib` is shipped with `RepeatMasker` (it's used in `RepeatProteinMask`)
* `RepeatMasker.lib` is generated by RepeatMasker's `configure` script from the installed libraries: Dfam, plus RepBase RepeatMasker Edition if it has been added. In RepeatMasker 4.1.0, this responsibility was moved into the `famdb.py` tool, which has a dependency on `python-h5py` (or however it is named in the bioconda repositories). `RepeatMasker.lib` is used by `RepeatModeler`.
* `configure` runs `makeblastdb` to generate BLAST format DBs for both of those files.

I am not sure why `RepeatMasker.lib` is 0 bytes long. Maybe there was an error in the environment or dependency setup; is there a way to access the build logs for the latest version of the `repeatmasker` package?

**Comment by Juke34** [comment] 2020-09-22 07:02
Here for the build, under building and testing:  
https://app.circleci.com/pipelines/github/bioconda/bioconda-recipes/32719/workflows/f3bcafb0-dca9-4564-935d-a675ab423d2f/jobs/123514
I can see
```
19:15:26 BIOCONDA INFO (OUT) RepeatMasker Configuration Program
19:15:26 BIOCONDA INFO (OUT) Rebuilding RepeatMaskerLib.embl master library
19:15:26 BIOCONDA INFO (OUT)     Reading Artefacts.embl database...
19:15:26 BIOCONDA INFO (OUT)   - Read in 9 sequences from $PREFIX/share/RepeatMasker/Libraries/Artefacts.embl
19:15:28 BIOCONDA INFO (OUT)     Reading Dfam.embl database...
19:15:28 BIOCONDA INFO (OUT)   - Read in 6915 sequences from $PREFIX/share/RepeatMasker/Libraries/Dfam.embl
19:15:29 BIOCONDA INFO (OUT)   Saving RepeatMaskerLib.embl library...
19:15:29 BIOCONDA INFO (OUT) RepeatMaskerLib.embl: 6924 total sequences.
19:15:29 BIOCONDA INFO (OUT) Building FASTA version...Building RMBlast frozen libraries..
19:15:32 BIOCONDA INFO (OUT) The program is installed with a the following repeat libraries:
19:15:32 BIOCONDA INFO (OUT)   Dfam database version Dfam_3.1
19:15:32 BIOCONDA INFO (OUT)   RepeatMasker Combined Database: Dfam-Dfam_3.1
19:15:32 BIOCONDA INFO (OUT) Further documentation on the program may be found here:
19:15:32 BIOCONDA INFO (OUT)   $PREFIX/share/RepeatMasker/repeatmasker.help
```

**Comment by cement-head** [comment] 2020-09-22 11:33
Hello,

This is not a conda install, but rather a "traditional" install on Ubuntu 18.04 LTS.  RepeatModeller is 2.01; RepeatMasker is 4.1.1. I installed RepeatMasker first (and dependencies), and then RepeatModeller (and dependencies).  I then ran RepeatModeller - without re-running the RepeatMasker <./configure> script.  I got the error.  

I have now re-run the RepeatMasker <.configure> script and looks as if I've generated the missing files that spat out the initial error.  I've started the process over again (63 hours), and hope it completes properly this time around.

![Screenshot from 2020-09-22 07-30-10](https://user-images.githubusercontent.com/1056700/93877059-d4e80400-fca5-11ea-8a96-a3811f37ef6c.png)

**Comment by jebrosen** [comment] 2020-09-22 15:10
@Juke34 It seems I misunderstood; I thought bioconda had already updated to the very latest version of RepeatMasker (4.1.1). I see now your PR only updated to 4.1.0. RepeatMasker 4.1.1 is more verbose about errors that happen in the failed step `Building FASTA libraries` than 4.1.0. I will try to replicate troubleshoot the build failure locally and see what's going on there.

---

@cement-head That is unexpected; it should be enough to run each configure script only one time at installation. If you have any way to replicate it, or any logs or output from the first time the configure script failed, please report it as an issue to https://github.com/rmhubley/RepeatMasker (since it's not a problem with the bioconda recipe).

**Comment by cement-head** [comment] 2020-09-22 16:03
Okay, will do - I'll look and if the logs are there, I will file them. Thx.

**Comment by cement-head** [comment] 2020-09-22 16:07
> Hello, I had the exact same issue.
> What I had to do is run `./configure` again. I think configure includes downloading the database and make a blast database.
> 
> ```
> cd $(dirname $(which RepeatMasker))/../share/RepeatMasker
> # ./configure downloads required databases
> echo -e "\n2\n$(dirname $(which rmblastn))\n\n5\n" > tmp && ./configure < tmp
> ```
> 
> It should look like this
> 
> ```
> ls $(dirname $(which RepeatMasker))/../share/RepeatMasker/Libraries
> # Artefacts.embl  Dfam.hmm       RepeatAnnotationData.pm  RepeatMasker.lib.nin  RepeatPeps.lib      RepeatPeps.lib.psq
> # CONS-Dfam_3.0   README.meta    RepeatMasker.lib         RepeatMasker.lib.nsq  RepeatPeps.lib.phr  RepeatPeps.readme
> # Dfam.embl       RMRBMeta.embl  RepeatMasker.lib.nhr     RepeatMaskerLib.embl  RepeatPeps.lib.pin  taxonomy.dat
> ```
> 
> Hope it helps. (I'm using RepeatMasker 2.0.1)
> 
> repeatmasker 4.0.9_p2 pl526_2 bioconda
> repeatmodeler 2.0.1 pl526_0 bioconda
> repeatscout 1.0.6 h516909a_1 bioconda

Yep, re-running <./configure> again for RepeatMasker, _**after**_ installing RepeatModeller seems to be necessary; even though it should not be required.  Will report as bug for RepeatMasker/RepeatModeller outside of this bioconda/conda repo.

**Comment by jebrosen** [comment] 2020-09-23 18:21
@Juke34 This looks like the problem affecting the latest package, after I modified a few files to get better error output:

```
17:42:43 BIOCONDA INFO (ERR) sh: /opt/conda/conda-bld/repeatmasker_1600882772077/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/share/RepeatMasker/util/buildRMLibFromEMBL.pl: /opt/conda/conda-bld/repeatmasker_1600882772077/_h_env_placehold_placehold_pla: bad interpreter: No such file or directory
```

In RepeatMasker 4.1.0, `buildRMLibFromEMBL.pl` was the program that generated `RepeatMasker.lib`. `configure` inserts the path to the running `perl` interpreter into the shebang line of every script that comes with `RepeatMasker`; it looks like it might have been cut off, breaking the path? That is a *lot* of `placehold_`. I don't know if this is a problem with `configure`, the path length, or something else. I also don't know if it's only a problem during `build.sh`, or maybe even after installation.

RepeatMasker 4.1.1 uses a different library format and a different program (`famdb.py`) to generate `RepeatMasker.lib`, so I expect it to either work completely fine or fail for a different reason on this same step. For that reason, I think it would be more constructive to update than to try to fix this version of the package.

**Comment by insectnate** [comment] 2020-10-19 22:53
I am still getting this error 
Missing /home1/miniconda3/share/RepeatMasker/Libraries/RepeatMasker.lib.nsq!
Please rerun the configure program in the RepeatModeler directory
before running this script.

when trying to generate the 
consensi.fa.classified  file
Using
RepeatClassifier -consensi consensi.fa

I don't quite follow all the above discussion on how to fix this. Where in the conda bin directory should the .lib.nsq file be placed?
Thanks for any help.

Nathan

**Comment by mudithekanayake** [comment] 2020-10-25 22:07
> Hello, I had the exact same issue.
> What I had to do is run `./configure` again. I think configure includes downloading the database and make a blast database.
> 
> ```
> cd $(dirname $(which RepeatMasker))/../share/RepeatMasker
> # ./configure downloads required databases
> echo -e "\n2\n$(dirname $(which rmblastn))\n\n5\n" > tmp && ./configure < tmp
> ```
> 
> It should look like this
> 
> ```
> ls $(dirname $(which RepeatMasker))/../share/RepeatMasker/Libraries
> # Artefacts.embl  Dfam.hmm       RepeatAnnotationData.pm  RepeatMasker.lib.nin  RepeatPeps.lib      RepeatPeps.lib.psq
> # CONS-Dfam_3.0   README.meta    RepeatMasker.lib         RepeatMasker.lib.nsq  RepeatPeps.lib.phr  RepeatPeps.readme
> # Dfam.embl       RMRBMeta.embl  RepeatMasker.lib.nhr     RepeatMaskerLib.embl  RepeatPeps.lib.pin  taxonomy.dat
> ```
> 
> Hope it helps. (I'm using RepeatMasker 2.0.1)
> 
> repeatmasker 4.0.9_p2 pl526_2 bioconda
> repeatmodeler 2.0.1 pl526_0 bioconda
> repeatscout 1.0.6 h516909a_1 bioconda

Can you please describe this line? I'm new to this.
 `echo -e "\n2\n$(dirname $(which rmblastn))\n\n5\n" > tmp && ./configure < tmp`

**Comment by insectnate** [comment] 2020-10-25 22:34
So i ran the above code you suggest in the miniconda share dir. 
cd $(dirname $(which RepeatMasker))/../share/RepeatMasker
# ./configure downloads required databases
echo -e "\n2\n$(dirname $(which rmblastn))\n\n5\n" > tmp && ./configure < tmp

But the directory still only looks like this. 
Artefacts.embl  README.meta              RepeatMaskerLib.embl       RepeatPeps.lib           RepeatPeps.readme
Dfam.embl       RepeatAnnotationData.pm  RepeatMasker.lib.ndb       RepeatPeps.lib.pdb       RMRBMeta.embl
Dfam.hmm        RepeatMasker.lib         RepeatMasker.lib.ndb-lock  RepeatPeps.lib.pdb-lock  taxonomy.dat

**Comment by insectnate** [comment] 2020-10-25 22:34
I configured it to use HMMER3.1 however. Would this be the problem?

**Comment by mbnmbn00** [comment] 2020-10-25 22:39
@mudithekanayake,
 If you run `./configure`, the interactive configuration process will popup.
Five configurations required:
\n
2\n
$(dirname $(which rmblastn))\n
\n
5\n

For the first `\n`, you type the return key to use the default value.
For the second `2\n`, you type 2 and the return key to choose 2.
... and so on.

Of course, you can do it in the interactive mode by setting one by one, but I was suggesting a kind of shortcut.

**Comment by mbnmbn00** [comment] 2020-10-25 22:40
@insectnate I don't think that would be a problem.
Try it out!

**Comment by insectnate** [comment] 2020-10-25 22:43
I did that and still get a Library directory of 
Artefacts.embl  README.meta              RepeatMaskerLib.embl       RepeatPeps.lib           RepeatPeps.readme
Dfam.embl       RepeatAnnotationData.pm  RepeatMasker.lib.ndb       RepeatPeps.lib.pdb       RMRBMeta.embl
Dfam.hmm        RepeatMasker.lib         RepeatMasker.lib.ndb-lock  RepeatPeps.lib.pdb-lock  taxonomy.dat

**Comment by mbnmbn00** [comment] 2020-10-25 23:06
Can you do the `./configure` and configure the settings one by one?

**Comment by insectnate** [comment] 2020-10-26 02:18
I did the ./configure where I am prompted to confirm the $PATH to each of the dependencies. I have tried it both with specifying RMBlast and HMMER3.1 but never get the makeblastdb files shown above. Is there another way to do configure that I am missing where there are more settings?

**Comment by mbnmbn00** [comment] 2020-10-26 02:22
1) I recommend creating a new environment and try it again.
2) Actually, if you look at the above comments, `makeblastdb` does enough job for you.
```
 makeblastdb -dbtype nucl -in ${CONDA_PREFIX}/share/RepeatMasker/Libraries/RepeatMasker.lib
```

**Comment by insectnate** [comment] 2020-10-26 02:24
Ok I will try that. By this do you mean deleting the conda install of RepeatMasker and installing again?

Thanks for all your help. 

Nathan

**Comment by mbnmbn00** [comment] 2020-10-26 02:26
Yes. Or, you could create another environment name.

**Comment by michaelkarlcoleman** [comment] 2020-10-26 22:17
Possibly related, the script `queryRepeatDatabase.pl` seems not to run because `FastaDB.pm` is not in `$PERL5LIB`.  (It's in `.../share/RepeatMasker/`.)

If I manually add that to `$PERL5LIB`, the script then fails with
```
No repeat libraries found!  At a minimum Dfam.embl, Dfam.hmm
or RepBase RepeatMasker Edition is required to run.  Please download
 and install the latest Dfam libraries.

Died at /packages/miniconda/20190102/envs/rm-edta-mcurry-20201021/share/RepeatMasker/LibraryUtils.pm line 386.
```

Note also for the above comments, I'm pretty sure it's not kosher to modify files/dirs in the conda tree after install by conda.  I think this breaks conda.

**Comment by Masa918** [comment] 2020-11-04 06:08
I had a same issue that RepeatMasker.lib and its blastdb by RepeatMasker configure. The solution I could was download the previous version-4.1.0 of RepeatMasker independently to conda.

**Comment by jebrosen** [comment] 2020-11-05 23:51
Now that #25163 is complete, I was able to download `repeatmasker` 4.1.1 from the bioconda repositories and `RepeatModeler` successfully finished, including the classification step, on a test sequence file. I think that was the last remaining issue reported in this thread; hopefully this update is also working well for others.

There are still a few reasons one might prefer a manual installation, for example the LTR structural search method introduced RepeatModeler 2.0 requires some dependencies that are not yet in bioconda.

**Comment by JuliaLopezDelgado** [comment] 2021-08-17 11:36
I recently had the same issue as described above, with the error message "missing /RepeatMasker/Libraries/RepeatPeps.lib.psq" when I tried to run RepeatClassifier. Just in case anyone else experiences this issue, I solved it by re-configuring RepeatMasker and manually downloading all the libraries from https://home.cc.umanitoba.ca/~psgendb/doc/BIRCH/doc/local/pkg/RepeatMasker/Libraries/ to the directory RepeatMasker/Libraries.

**Comment by Juke34** [comment] 2021-08-17 11:52
@JuliaLopezDelgado Please specify the version you have used. Because depending the version the problem is solved.

**Comment by JuliaLopezDelgado** [comment] 2021-08-17 11:54
> @JuliaLopezDelgado Please specify the version you have used. Because depending the version the problem is solved.

I am using RepeatMasker v.4.1.2 and RepeatModeler v.2.0.2

**Comment by jebrosen** [comment] 2021-08-18 17:37
@JuliaLopezDelgado Bioconda had packages for RepeatMasker 4.1.1 (broken) and RepeatMasker 4.1.2-p1 (fixed), skipping over RepeatMasker 4.1.2 (FWIW, also fixed). Did you mean 4.1.2-p1?

The libraries available at home.cc.umanitoba.ca are over 10 years old. It is only by chance that they could even work today - and worse, old libraries might appear to work and silently fail or produce wrong/misleading results. For that reason I generally recommend against trying to "mix" files from new and old versions of RepeatMasker and RepeatModeler.

**Comment by jebrosen** [comment] 2021-10-13 18:10
@JuliaLopezDelgado It looks like you are missing the file `RepeatPeps.lib.psq`, but you ran a command to generate `RepeatMasker.lib.nsq`. Try this one instead: `makeblastdb -dbtype prot -in RepeatMasker/Libraries/RepeatPeps.lib`. I hope this resolves your problem!

I noticed in your file list that there are files from multiple versions of RepeatMasker. Mixing files from different versions can cause confusion and sometimes errors, so we usually recommend installing updates to RepeatMasker and RepeatModeler in new directories.

If you continue experiencing issues with a manual installation of RepeatMasker/RepeatModeler, please see also our GitHub pages and issue trackers for these projects, which are not specific to bioconda: https://github.com/rmhubley/RepeatMasker/issues, https://github.com/Dfam-consortium/RepeatModeler/issues.

**Comment by JuliaLopezDelgado** [comment] 2021-10-14 10:32
Thank you @jebrosen! The makeblastdb command generated the .psq file and RepeatClassifier now works. 

I didn't install multiple versions of RepeatMasker, so I'm unsure why there are files from different versions. These are the commands I used to install it:
`wget http://www.repeatmasker.org/RepeatMasker/RepeatMasker-4.1.2-p1.tar.gz`
`gunzip RepeatMasker-4.1.2-p1.tar.gz`
`tar xvf RepeatMasker-4.1.2-p1.tar.gz`
`wget https://www.dfam.org/releases/Dfam_3.2/families/Dfam.h5.gz`
`gunzip Dfam.h5.gz`
`mv Dfam.h5 ./RepeatMasker/Libraries`
`cd ./RepeatMasker`
`perl ./configure`
`makeblastdb -dbtype prot -in ./Libraries/RepeatPeps.lib`

Does this look okay? 

Thank you!
Julia

**Comment by duoqingxiaotaiyang** [comment] 2023-04-06 08:23
but when i type makeblastdb -dbtype prot -in RepeatMasker/Libraries/RepeatPeps.lib, it shows that  "Error: NCBI C++ Exception:
    T0 "/opt/conda/conda-bld/rmblast_1648559906758/work/c++/src/objtools/blast/seqdb_writer/build_db.cpp", line 1019: Error: (CMultisourceException::eInvalid) BLASTDB::ncbi::CBuildDatabase::CreateDirectories() - Failed to create directory 'Libraries'
",how can i solve this problem?

**Comment by Juke34** [comment] 2023-04-06 08:31
The path to the lib is wrong try:
`makeblastdb -dbtype prot -in $(dirname $(which RepeatMasker))/../share/RepeatMasker/Libraries/RepeatPeps.lib`

Before you run the command check if the path is correct:
`ls -l $(dirname $(which RepeatMasker))/../share/RepeatMasker/Libraries/`

**Comment by duoqingxiaotaiyang** [comment] 2023-04-09 08:28
> 

Thank you so much for letting me know !! now repeatmodeler can work properly

**Closed** 2023-10-19 12:12 UTC
