### ISSUE TITLE
Cannot install WhatsHap in Python 3.11 environment

### ISSUE THREAD

**Issue by PlatonB** [bioconda/bioconda-recipes#44413] opened 2023-11-22 16:47 UTC
Ubuntu 20.04.1
conda 23.10.0
Python 3.11.6

```
conda install whatshap=2.1
```

```
<...>
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package whatshap-2.1-py310h0dbaff4_0 requires python >=3.10,<3.11.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ pin-1 is installable and it requires
│  └─ python 3.11.* , which can be installed;
└─ whatshap 2.1**  is not installable because there are no viable options
   ├─ whatshap 2.1 would require
   │  └─ python >=3.10,<3.11.0a0 , which conflicts with any installable versions previously reported;
   ├─ whatshap 2.1 would require
   │  └─ python >=3.8,<3.9.0a0 , which conflicts with any installable versions previously reported;
   └─ whatshap 2.1 would require
      └─ python >=3.9,<3.10.0a0 , which conflicts with any installable versions previously reported.

Pins seem to be involved in the conflict. Currently pinned specs:
 - python 3.11.* (labeled as 'pin-1')
```

**Comment by jmarshall** [comment] 2023-11-23 00:14
See #37805.

**Comment by corneliusroemer** [comment] 2023-12-20 20:48
Bioconda packages that are _not_ noarch currently cannot be installed in Python 3.11/12

**Comment by corneliusroemer** [comment] 2023-12-20 20:50
Closing as duplicate of #37805 - this should resolve itself as soon as Python 3.11 is supported by bioconda

**Closed by corneliusroemer** 2023-12-20 20:50 UTC
