### ISSUE TITLE
Could we run simulate-travis.py with zlib requirement in a recipe ?

### ISSUE THREAD

**Issue by oinizan** [bioconda/bioconda-recipes#6153] opened 2017-09-27 08:29 UTC
I’m trying to use simulate-travis.py for a recipe with a zlib requirement (for the build). The build process in the docker container (tmp-bioconda-builder) leads to an assertion error:

`Can't build /opt/recipe due to environment creation error:`
`AssertionError(‘/opt/conda/pkgs/zlib-1.2.11-0',)`

When I run the conda-build command directly in the container (with the —debug option) it seems that the directory where the zlib is extracted already exists.  

`DEBUG:conda.core.package_cache:Traceback (most recent call last):
  File "/opt/conda/lib/python3.5/site-packages/conda/core/package_cache.py", line 505, in _execute_action
    action.execute()`
  `File "/opt/conda/lib/python3.5/site-packages/conda/core/path_actions.py", line 824, in execute
    extract_tarball(self.source_full_path, self.target_full_path)`
  `File "/opt/conda/lib/python3.5/site-packages/conda/gateways/disk/create.py", line 105, in extract_tarball`
    `assert not lexists(destination_directory), destination_directory`
`AssertionError: /opt/conda/pkgs/zlib-1.2.11-0`

A prior installation of zlib seems to be done (maybe for extracting requirements …)

Any ideas ?

**Comment by daler** [comment] 2017-09-27 13:16
@oinizan I don't think I've ever seen this and I can't immediately think of a reason this would be happening. So it will take some playing around with a recipe that reproduces the error. Do you have a PR where this is happening?

**Comment by oinizan** [comment] 2017-09-27 13:47
The recipe is simple, files are here:
[meta.yaml.txt](https://github.com/bioconda/bioconda-recipes/files/1337386/meta.yaml.txt)
[build.sh.txt](https://github.com/bioconda/bioconda-recipes/files/1337389/build.sh.txt)

@daler do you prefer a PR  ? (I did not make it because my Travis CI fails)
Thanks for your help.

**Comment by daler** [comment] 2017-09-27 14:01
Thanks. A PR from a branch of bioconda-recipes repo would be helpful because then others could take a look at the log and make changes/fixes directly to the PR. We have recipes failing on travis all the time, no worries about that.

**Comment by oinizan** [comment] 2017-09-27 14:14
@daler  done see PR #6158
Thanks again

**Comment by daler** [comment] 2017-10-16 01:12
Closed by #6158

**Closed by daler** 2017-10-16 01:12 UTC
