### ISSUE TITLE
Recipes to fix due to failing nightly build

### ISSUE THREAD

**Issue by johanneskoester** [bioconda/bioconda-recipes#1744] opened 2016-06-14 14:35 UTC
- [x] pysam/0.8.3 ([glibc error due to precompiled htslib?](https://travis-ci.org/bioconda/bioconda-tests/jobs/137505202))
- [x] merfishtools ([weird conda dependency conflict that cannot be reproduced locally](https://travis-ci.org/bioconda/bioconda-tests/jobs/137505208#L1452))
- [x] mapsplice ([dependency conflict due to incorrect build string](https://travis-ci.org/bioconda/bioconda-tests/jobs/138253634#L1466))
- [x] osra/2.0.1 ([Missing shared library](https://travis-ci.org/bioconda/bioconda-tests/jobs/139373629#L1682))
- [x] emboss (Error: File /anaconda/conda-bld/work/EMBOSS-6.5.7/emboss/acd/needle.acd line 0: ACD file not opened)
- [x] eigensoft ([test case problem](https://travis-ci.org/bioconda/bioconda-tests/jobs/152189988#L1841))
- [x] prodigal ([test case problem](https://travis-ci.org/bioconda/bioconda-tests/jobs/152189988#L1841))
- [x] gfold ([test case problem](https://travis-ci.org/bioconda/bioconda-tests/jobs/152190024#L1844))

**Comment by bgruening** [comment] 2016-06-14 15:20
@johanneskoester I will work on pysam today if this is ok.

**Comment by johanneskoester** [comment] 2016-06-15 08:00
Sure, thanks!

**Comment by johanneskoester** [comment] 2016-06-22 08:24
Any update on pysam?

**Comment by bgruening** [comment] 2016-06-23 08:42
@johanneskoester is this still a problem with the newer pysam? I tried to reproduce the error of the old pysam version locally but never saw an error. I thought it was fixed with the new pysam version. Do you have a link to a recent pysam failure?

**Comment by johanneskoester** [comment] 2016-06-23 12:29
You are right :-). I can't find the failure anymore.

**Comment by johanneskoester** [comment] 2016-06-23 12:30
Oh no, it is just in a diffferent subdag:
https://travis-ci.org/bioconda/bioconda-tests/jobs/139373626#L1894

**Comment by johanneskoester** [comment] 2016-06-23 12:31
It is the old version, but we have a recipe specifically for that version. So if somebody wants to keep this package, we should make sure it works.

**Comment by johanneskoester** [comment] 2016-07-04 12:49
@simonvh can you have a look at the emboss error? It looks like the build environment has leaks into the test case when the package is being built, but some file is missing when you invoke e.g. needle after a new installation.

**Comment by simonvh** [comment] 2016-07-04 13:14
I will have a look!

**Comment by JohnGreeley** [comment] 2016-08-03 22:25
The emboss problem is for any emboss tool that uses these ACD files, I had a similar problem with seqret:

`Error: File /anaconda/conda-bld/work/EMBOSS-6.5.7/emboss/acd/seqret.acd line 0: ACD file not opened`

**Comment by bgruening** [comment] 2016-08-04 13:02
@JohnGreeley the reason is that emboss compiles the path to the acd files into the binaries. This is something like `/anaconda/build/...`. I propose the following, for every tools we write a short shell script that exports the path to ACD files.

The following should work:
```
export EMBOSS_ACDROOT=../share/EMBOSS/acd/
seqret "$@"
```

Do you have time to work on this?

**Comment by bgruening** [comment] 2016-08-13 00:02
@johanneskoester @JohnGreeley EMBOSS is fixed in https://github.com/bioconda/bioconda-recipes/pull/2095
Here is a Docker container. with tests: https://github.com/mulled/mulled/pull/134

I will check this one off.

**Comment by bgruening** [comment] 2016-08-13 00:03
Only one left.

**Comment by johanneskoester** [comment] 2016-08-13 08:05
Great work, Björn!! Thank you so much!

**Comment by bgruening** [comment] 2016-08-13 08:47
Your welcome. One tool left and the build-infrastructure migration :)
Should be fix a date and coordinate this all a little bit and get everything done in one shoot? We also need to migrate the r/perl packages in it's own subdir and so on.

**Comment by bgruening** [comment] 2016-08-13 11:56
@johanneskoester osra is fixed in: https://github.com/bioconda/bioconda-recipes/pull/2135

These kind of errors can happen at any time, as we do not pin every library. So rebuilding at a later time point can cause such errors :(

What's left on this front?

**Comment by johanneskoester** [comment] 2016-08-15 07:43
@bgruening that's right. We agreed at some point that it is a good strategy to only pin once the need occurs. Otherwise, we would end up pinning literally everything, just to be sure. However, for many libs it is not clear if they use semantic versioning. Hence, this would significantly prolong the review of each PR. I am still in favor of doing it in the trial and error way like it is now.

**Comment by bgruening** [comment] 2016-08-15 07:49
@johanneskoester I'm fine with this, as we have a Docker container as backup. I'm just a little bit worried about the disc space at anaconda.com? Do we replace old unpinned version? Should we not care?

**Comment by johanneskoester** [comment] 2016-08-15 07:58
In principle, we could replace old builds. But for reproducibility (even of errors), I would like to give the guarantee that no build number ever disappears. At the moment, we are at 26GB of 100GB storage. So there is still plenty of room. As our knowledge about which libraries to pin grows, there will be less and less such events. I think this will become a no-issue before we hit the 100GB limit. Also, at the time we hit the limit, we might have the opportunity to move certain non-bioinformatics packages to conda-forge or the default channel to free up further space. Finally, I am sure that continuum will give us extra space if we need it.

**Comment by bgruening** [comment] 2016-08-15 08:10
@johanneskoester I like your optimism :)
The point is that currently it is not strictly reproducible, as dependency changes and package will break. It's hard to know which dependency was available at a certain time in the past. So this reproducible argument does not count for such packages. But I'm fine to keep all builds as well, as long as we don't have to worry about space!

Let me know what else needs to be done to get the tests working. I would like to activate conda-forge as dependency :)
Thanks.

**Comment by johanneskoester** [comment] 2016-08-15 08:21
Well, if we guarantee that no build number disappears, people can achieve full reproducibility using environment.yml files that list all packages of the environment, including the build number and recursive dependencies. This is very easy with the env export command. 

We have  a weird error in the last weekly tests on osx: [here](https://travis-ci.org/bioconda/bioconda-tests/jobs/152190039#L217). It seems to be a bug in conda, but I don't yet understand why it did not occur in bioconda-recipes. Let me know if you have an idea what's going on.

**Comment by bgruening** [comment] 2016-08-22 20:19
@johanneskoester eigensoft and the gfold links are fine and there is no error.

**Comment by johanneskoester** [comment] 2016-08-23 12:47
Thanks!

**Comment by peterjc** [comment] 2017-05-26 10:50
Can this be closed? It looks like everything listed in the issue has been ticked off..

**Comment by bgruening** [comment] 2017-05-26 16:16
Thanks @peterjc

**Closed** 2017-05-26 16:16 UTC
