### ISSUE TITLE
perl-db-file is broken

### ISSUE THREAD

**Issue by nextgenusfs** [bioconda/bioconda-recipes#24688] opened 2020-10-05 20:43 UTC
This is a dependency of TransDecoder and PASA -- perhaps other packages. It seems to "install" "properly", however I think it is not compiling correctly as its non-functional.

Steps to reproduce:

```
$ conda create -n db-file-test perl-db-file
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.4
  latest version: 4.8.5

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /shared_miniconda3/envs/db-file-test

  added / updated specs:
    - perl-db-file


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libgcc-ng-9.3.0            |      h5dbcf3e_17         7.8 MB  conda-forge
    libgomp-9.3.0              |      h5dbcf3e_17         378 KB  conda-forge
    libstdcxx-ng-9.3.0         |      h2ae2ef3_17         4.0 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        12.2 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_gnu
  libdb              conda-forge/linux-64::libdb-6.2.32-he1b5a44_0
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.3.0-h5dbcf3e_17
  libgomp            conda-forge/linux-64::libgomp-9.3.0-h5dbcf3e_17
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.3.0-h2ae2ef3_17
  perl               conda-forge/linux-64::perl-5.26.2-h516909a_1006
  perl-db-file       bioconda/linux-64::perl-db-file-1.852-pl526h14c3975_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
libgomp-9.3.0        | 378 KB    | ############################################################################################################################################################# | 100%
libstdcxx-ng-9.3.0   | 4.0 MB    | ############################################################################################################################################################# | 100%
libgcc-ng-9.3.0      | 7.8 MB    | ############################################################################################################################################################# | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

Now activate and test

```
$ conda activate db-file-test


(db-file-test) $ perl -MDB_File -e 1
Can't load '/shared_miniconda3/envs/db-file-test/lib/site_perl/5.26.2/x86_64-linux-thread-multi/auto/DB_File/DB_File.so' for module DB_File: libdb-6.1.so: cannot open shared object file: No such file or directory at /shared_miniconda3/envs/db-file-test/lib/5.26.2/XSLoader.pm line 96.
 at /shared_miniconda3/envs/db-file-test/lib/site_perl/5.26.2/x86_64-linux-thread-multi/DB_File.pm line 257.
Compilation failed in require.
BEGIN failed--compilation aborted.


(db-file-test) $ which perl
/shared_miniconda3/envs/db-file-test/bin/perl
```

**Comment by Lix1993** [comment] 2020-10-09 00:52
star-fusion broken with same reason

**Comment by daissi** [comment] 2020-10-13 08:22
FEELnc is also affected

**Comment by abretaud** [comment] 2020-10-14 11:18
The problem is that perl-db-file was compiled with libdb 6.1, while installing it now installs libdb 6.2

**Comment by abretaud** [comment] 2020-10-14 11:20
I guess libdb should be added to https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml

**Comment by abretaud** [comment] 2020-10-21 14:17
It should be fixed in https://github.com/bioconda/bioconda-recipes/pull/24841 now, closing this issue

**Closed by abretaud** 2020-10-21 14:17 UTC
Labels: help wanted

**Comment by nextgenusfs** [comment] 2020-10-21 14:27
Fantastic thanks @abretaud
