### ISSUE TITLE
homer recipe issue for linux version

### ISSUE THREAD

**Issue by cokelaer** [bioconda/bioconda-recipes#5185] opened 2017-07-12 07:33 UTC
Homer is a perl package. Under Mac I believe the installation works well. However, under Linux
it seems that the installation is not correct. Indeed, the binaries (e.g GenomeOntology.pl) do not do anything. In fact, the binaries are link to the perl code in ./share/homer/ directory and those files are all empty. 

Could not find a solution yet but reported the issue here. 

In the bioconda channel, we can see the Mac files are 20 Mb and the linux ones only a few kb: https://anaconda.org/bioconda/homer/files

FYI, I put @bioninja, @simonvh and myself as assignees because it was discussed in the recipes but feel free to change this assignment.

**Comment by simonvh** [comment] 2017-07-12 07:37
The funny thing is that `conda-build` locally results in a package that is perfectly fine.

**Comment by simonvh** [comment] 2017-07-12 07:50
Ok, some updates. I think the issue is that the `configureHomer.pl` script has some additional dependences (wget, gcc) that are not present when building. This means that a) this script apparently fails silently (not good) and that b) the tests for the recipe are not sufficient (also not good). I will try fixing this and see if that works.

**Comment by simonvh** [comment] 2017-07-12 08:11
`configureHomer.pl` indeed exits with an error code 0 (and a printed warning, which is invisible). Turns out also `zip` and `unzip` have to explicitly be defined as dependencies.  I added a `homer2` call to the tests. This is compiled at the end of the script, so this should be a good check if the whole script ran without trouble.

See PR here: #5186

**Comment by simonvh** [comment] 2017-07-12 08:32
Should be fixed.

**Closed** 2017-07-13 05:45 UTC
Labels: bug, help wanted
