### ISSUE TITLE
samtools on macosx is incompatible with ncurses from defaults channel

### ISSUE THREAD

**Issue by s22chan** [bioconda/bioconda-recipes#13488] opened 2019-02-04 17:59 UTC
I'm getting:

```
dyld: Symbol not found: _stdscr
  Referenced from: /opt/conda/miniconda3/envs/test/bin/samtools
  Expected in: /opt/conda/miniconda3/envs/test/bin/../lib/libncursesw.6.dylib
 in /opt/conda/miniconda3/envs/test/bin/samtools
```

with:
```
ncurses:         6.1-h0a44026_1         
samtools:        1.9-hb029021_5           bioconda
```

this version worked before:
```
ncurses:         6.1-h0a44026_1           
samtools:        1.9-h8ee4bcc_1           bioconda
```

**Comment by tomkinsc** [comment] 2019-02-06 15:34
Thanks for the issue report. Until the underlying issue is resolved, the older build can be installed via:
`conda install -c bioconda samtools=1.9=h8ee4bcc_1`

For testing, what samtools command resulted in this error?

It looks like this PR https://github.com/bioconda/bioconda-recipes/pull/13464 may have broken samtools.
Related:
https://github.com/conda-forge/conda-forge.github.io/issues/701
@bioconda/core: Maybe we should think about [template pinning](https://github.com/bioconda/bioconda-recipes/blob/master/scripts/env_matrix.yml) openssl to match the predominant version used upstream by conda-forge? (`1.0.2p`?)

**Comment by dpryan79** [comment] 2019-02-06 15:38
Openssl is pinned. The issue is that `conda install` will ignore the pinning of packages already installed in an environment.

**Comment by Marcoleta-AE** [comment] 2019-02-17 14:40
I experienced the same issue. Some weeks ago it was working without problems, I have no idea what changed to cause this issue... maybe some MacOS update?. I'm working under macOS High Sierra 10.13.6. Now the details:

Some First, when calling samtools I got this already reported issue:

dyld: Library not loaded: @rpath/libcrypto.1.0.0.dylib
  Referenced from: /Users/andresmarcoleta/anaconda3/bin/samtools
  Reason: image not found
Abort trap: 6

After searching for info I got this solution:

https://gist.github.com/aklap/e885721ef15c8668ed0a1dd64d2ea1a7

It worked but when calling samtools now the error reported in this thread appeared:

dyld: Symbol not found: _stdscr
  Referenced from: /Users/andresmarcoleta/anaconda3/bin/samtools
  Expected in: /Users/andresmarcoleta/anaconda3/bin/../lib/libncursesw.6.dylib
 in /Users/andresmarcoleta/anaconda3/bin/samtools
Abort trap: 6

So, based on tomkinsc's comment, I tried installing the older build 

Now, everything is OK when calling samtools. Actually, I started detecting this issue when trying to run Unicycler... after checking dependencies, the program stopped indicating that samtools was missing. I tried to reinstall samtools several times but it remained not recognized or unable to be called from Unicycler. Fortunately, after installing the old build, now Unicycler recognized samtools and run OK.

**Comment by dpryan79** [comment] 2019-02-17 20:48
ncurses is pinned as well. Once again `conda install` seems to ignore pinnings, please avoid using it.

**Comment by hisplan** [comment] 2019-02-20 16:06
Along with the SSL issue mentioned in #12100, only the following worked for me (as of Feb 20, 2019)
```bash
conda install -c bioconda samtools=1.9=h8ee4bcc_1 openssl=1.0
```

**Comment by s22chan** [comment] 2019-03-07 19:42
For posterity, it appears the anaconda channel ncurses is no longer compatible with samtools. The following works:

```
conda create -n test samtools conda-forge::ncurses
```

**Comment by dpryan79** [comment] 2019-03-07 19:53
There should actually be a compatible samtools now. I've started updating things for the new OpenSSL version and samtools was in the first PR merged of that. I'll make an announcement about the change in OpenSLL pinnings within the next couple hours.

**Comment by s22chan** [comment] 2019-03-12 21:34
@dpryan79 still broken wrt to ncurses from defaults:
```
ncurses                   6.1                  h0a44026_1
openssl                   1.1.1b               h1de35cc_1
samtools                  1.9                 h7c4ea83_11    bioconda
```

**Comment by dpryan79** [comment] 2019-03-13 13:07
@s22chan Actually, the most recent version of samtools is built against ncurses 6.1 and `conda create -n samtools_test samtools` on OSX works appropriately (at least for me). Are you still getting an error?

**Comment by s22chan** [comment] 2019-03-13 13:52
@dpryan79 can you `conda list` and confirm you got ncurses from defaults instead of conda-forge? I understand conda-forge priority is part of the bioconda instructions but as you can see, a lot of other people came across it incidentally.

**Comment by dpryan79** [comment] 2019-03-13 13:55
It's from conda-forge, as it should be:

```
mac884:~ ryan$ conda list
# packages in environment at /Users/ryan/miniconda3/envs/fubar:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.6             h1de35cc_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
curl                      7.64.0               heae2a1f_2    conda-forge
krb5                      1.16.3            hcfa6398_1001    conda-forge
libcurl                   7.64.0               he376013_2    conda-forge
libcxx                    7.0.0                h2d50403_1    conda-forge
libdeflate                1.0                  h1de35cc_1    bioconda
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libssh2                   1.8.0             hb1dc21d_1004    conda-forge
llvm-meta                 7.0.0                         0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
openssl                   1.1.1b               h1de35cc_1    conda-forge
samtools                  1.9                 h7c4ea83_11    bioconda
tk                        8.6.9             ha441bb4_1000    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
zlib                      1.2.11            h1de35cc_1004    conda-forge
```

**Comment by s22chan** [comment] 2019-03-13 13:57
I'll change the title to reflect that it doesn't work for defaults

**Comment by dpryan79** [comment] 2019-03-13 13:59
It shouldn't come from defaults, that suggests your channel order is wrong.

**Comment by jmarshall** [comment] 2019-03-28 15:59
(There's the relatively well-known openssl problem, and separately there's an ncurses problem.)

> For posterity, it appears the anaconda channel ncurses is no longer compatible with samtools.

FWIW the reason for this is that the anaconda channel ncurses has not had a fix equivalent to conda-forge/ncurses-feedstock#45 applied. This is what I was alluding to in https://github.com/samtools/samtools/issues/940#issuecomment-452654909 with “Provided the conda user has selected conda-forge for their ncurses […]”.

If there's somewhere to report bugs in or submit patches to anaconda channel packages, I can prepare a similar patch for that ncurses…

**Comment by coffee-and-genomics** [comment] 2019-07-24 15:33
I'm not sure why it worked, but this fixed my error:

1. `conda uninstall samtools`
2. `conda update --all`
3. `conda install samtools`

**Comment by bede** [comment] 2019-08-13 09:33
Still an issue it seems
```
(samtools) dcnmac30:multi bede$ conda env export
name: samtools
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2019.5.15=1
  - certifi=2019.6.16=py37_1
  - curl=7.65.2=ha441bb4_0
  - krb5=1.16.1=hddcf347_7
  - libcurl=7.65.2=h051b688_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libdeflate=1.0=h1de35cc_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=1
  - libssh2=1.8.2=ha12b0ac_0
  - ncurses=6.1=h0a44026_1
  - openssl=1.1.1c=h1de35cc_1
  - pip=19.1.1=py37_0
  - python=3.7.4=h359304d_0
  - readline=7.0=h1de35cc_5
  - samtools=1.9=h7c4ea83_11
  - setuptools=41.0.1=py37_0
  - sqlite=3.29.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
prefix: /Users/bede/conda/envs/samtools
```

**Comment by jmarshall** [comment] 2019-09-06 10:55
The samtools package now works with either conda-forge or defaults ncurses, as of `samtools-1.9-h8aa4d43_12`, i.e., since PR #17273.

**Comment by ialbert** [comment] 2020-07-18 00:14
The default samtools version seems to be again 1.4 and is broken:

On Mac OSX samtools won't work after installation:

    conda create --name test python=3.6
    conda activate test
    conda install samtools -y

invoking samtools:

```
samtools
dyld: Library not loaded: @rpath/libcrypto.1.0.0.dylib
  Referenced from: /Users/ialbert/miniconda3/envs/test/bin/samtools
  Reason: image not found
Abort trap: 6
```

**Comment by mbargull** [comment] 2020-07-18 00:28
@ialbert, seems like you are hitting https://github.com/conda/conda/issues/9905.
```sh
$ CONDA_SUBDIR=osx-64 conda create -dqnx python=3.6 samtools -c conda-forge -c bioconda 2>/dev/null | grep -E '::(samtools|htslib|openssl)'
  openssl            conda-forge/osx-64::openssl-1.1.1g-h0b31af3_0
  samtools           bioconda/osx-64::samtools-1.4.1-0
```
If you run `CONDA_REPODATA_FNS=repodata.json conda ...` instead of `conda ...` you get:
```sh
$ CONDA_REPODATA_FNS=repodata.json CONDA_SUBDIR=osx-64 conda create -dqnx python=3.6 samtools -c conda-forge -c bioconda 2>/dev/null | grep -E '::(samtools|htslib|openssl)'
  htslib             bioconda/osx-64::htslib-1.10.2-h422799e_1
  openssl            conda-forge/osx-64::openssl-1.1.1g-h0b31af3_0
  samtools           bioconda/osx-64::samtools-1.10-h457b48f_2
```

**Comment by ialbert** [comment] 2020-07-18 00:44
ok, if I got the gist of the advice in https://github.com/conda/conda/issues/9905 is that one has pin samtools to a known version. 

as for the second solution, is adding  `CONDA_REPODATA_FNS=repodata.json`  a universally good idea? Does it have any unexpected side effects, when say installing multiple packages at once?

**Comment by mbargull** [comment] 2020-07-18 00:58
`current_repodata.json` is a performance hack. The downside to `CONDA_REPODATA_FNS=repodata.json` is just performance. As for correctness, I currently recommend to use `CONDA_REPODATA_FNS=repodata.json` because `current_repodata.json` causes to much trouble.
(Using `current_repodata.json` *can* work in most cases when you are dealing with only one channel (the assumptions around that do not cover multiple channels, unfortunately). With Bioconda we have two channels, i.e., `-c conda-forge -c bioconda`. The reduced package set from `conda-forge`'s `current_repodata.json` does not take packages from `bioconda` into account and hence lacks `conda-forge` packages that are required to install recent versions of packages from `bioconda`.)

**Comment by mbargull** [comment] 2020-07-18 01:00
Overall it's an annoying situation because you either take long running times from `conda` or you risk broken workflows. I am more willing to take the former than the latter. It's still frustrating, though...

**Comment by mbargull** [comment] 2020-07-18 01:05
(Evaluation `mamba` as an alternative to `conda` is also an option, of course.)

**Comment by ialbert** [comment] 2020-07-18 01:13
TIL about `mamba` :-) 

As long as it works with pinning we'll go with that, seems like the simplest and most practical solution for students. We'll pay with a little tedium.

I can verify that pinning `samtools==1.10` does work. 

thanks for the suggestion

**Closed by ialbert** 2020-07-18 01:13 UTC

**Comment by s22chan** [comment] 2020-07-20 14:24
I'm not sure if the repodata is only a performance hack now because the conda-forge team has been using it to patch up dependencies (like adding the python ABI)

**Comment by mbargull** [comment] 2020-07-20 14:45
@s22chan, no that's a different matter. `repodata.json` != `current_repodata.json`.
`repodata-patches` on conda-forge are used to patch the `repodata.json` from https://conda-web.anaconda.org which is then made available via https://conda-static.anaconda.org (which the user gets served in the end).
`current_repodata.json` is a subset of the patched `repodata.json` on conda-static.anaconda.org and provided as a performance hack.

**Comment by s22chan** [comment] 2020-07-20 15:13
@mbargull ahhhh, thanks for the clarification
