### ISSUE TITLE
Azure Pipelines error with "No hosted parallelism has been purchased"

### ISSUE THREAD

**Issue by TobyBaril** [bioconda/bioconda-recipes#47856] opened 2024-05-13 08:03 UTC
I've come across an issue this morning which I think is responsible for all the failed tests across multiple packages in pull requests:

```
No hosted parallelism has been purchased or granted. To request a free parallelism grant, please fill out the following form https://aka.ms/azpipelines-parallelism-request
```

Likely you are already aware but thought it would be good to post for information for others who might not be aware.

**Comment by lskatz** [comment] 2024-05-13 16:04
Tagging ##41025 in case it's related

**Comment by ZhijianZhou01** [comment] 2024-05-16 08:48
No hosted parallelism has been purchased or granted. To request a free parallelism grant, please fill out the following form https://aka.ms/azpipelines-parallelism-request

#47914

**Comment by johanneskoester** [comment] 2024-05-17 04:45
Thanks for reporting. We have seen this and already try to get in personal contact with the Azure team for a while. So far, we have not received a response though.

**Comment by corneliusroemer** [comment] 2024-05-17 16:21
Duplicate of:
- https://github.com/bioconda/bioconda-recipes/issues/41025

**Closed by corneliusroemer** 2024-05-17 16:21 UTC
