### ISSUE TITLE
Installing trinity==2.4.0 results in non functional bowtie2 dependency

### ISSUE THREAD

**Issue by lparsons** [bioconda/bioconda-recipes#6637] opened 2017-11-06 21:42 UTC
Attempting to install `trinity==2.4.0` results in `bowtie=2.2.5=0` being installed. This is not the lastest bowtie2 build (there is a build 2) and it doesn't work. Also, attempting to install `bowtie==2.2.5` results in the broken build 0 install. However, first installing `bowtie=2.2.5_py36_2` does work and subsequently installing `trinity==2.4.0` into that envrionment results in `bowtie2 2.3.3.1-py36pl5.22.0_0` being installed. Then everything works.

This may be related to #6163?

**Comment by lparsons** [comment] 2017-11-06 22:14
Looks like this is a Conda bug: https://github.com/conda/conda/issues/6269

**Comment by mbargull** [comment] 2017-11-07 19:26
@bioconda/core : Explicitly avoiding the build `bowtie2=2.2.5-0` also works here:
<details><summary><code>
$ conda create --dry-run -n x -c conda-forge -c bioconda trinity 'bowtie2!=2.2.5-0'
</code></summary><p>

```
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /home/maba/code/miniconda3/envs/x:

The following NEW packages will be INSTALLED:

    bowtie:             1.2.1.1-py36pl5.22.0_0 bioconda   
    bowtie2:            2.3.3.1-py36pl5.22.0_0 bioconda   
    bzip2:              1.0.6-1                conda-forge
    ca-certificates:    2017.7.27.1-0          conda-forge
    certifi:            2017.7.27.1-py36_0     conda-forge
    collectl:           4.0.4-1                bioconda   
    curl:               7.55.1-0               conda-forge
    fastool:            0.1.4-1                bioconda   
    jellyfish:          2.2.6-0                bioconda   
    krb5:               1.14.2-0               conda-forge
    libgcc:             5.2.0-0                           
    libssh2:            1.8.0-2                conda-forge
    ncurses:            5.9-10                 conda-forge
    openjdk:            8.0.121-1                         
    openssl:            1.0.2l-0               conda-forge
    parafly:            r2013_01_21-0          bioconda   
    perl:               5.22.0.1-0             conda-forge
    perl-app-cpanminus: 1.7039-pl5.22.0_3      bioconda   
    perl-module-build:  0.4214-pl5.22.0_3      bioconda   
    perl-threaded:      5.22.0-pl5.22.0_12     bioconda   
    pip:                9.0.1-py36_0           conda-forge
    python:             3.6.3-1                conda-forge
    readline:           6.2-0                  conda-forge
    samtools:           1.5-1                  bioconda   
    setuptools:         36.6.0-py36_1          conda-forge
    slclust:            02022010-1             bioconda   
    sqlite:             3.13.0-1               conda-forge
    tbb:                2018_20170919-0        conda-forge
    tk:                 8.5.19-2               conda-forge
    trimmomatic:        0.36-5                 bioconda   
    trinity:            2.4.0-5                bioconda   
    wheel:              0.30.0-py_1            conda-forge
    xz:                 5.2.3-0                conda-forge
    zlib:               1.2.11-0               conda-forge
```
</p></details>

**Comment by mbargull** [comment] 2017-11-07 22:23
@bgruening marked that build as `broken`! But... Conda is a sneaky little devil 😠:
<details><summary><code>
$  conda create --dry-run -n x -c conda-forge -c bioconda trinity
</code></summary><p>

```
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /home/maba/code/miniconda3/envs/x:

The following NEW packages will be INSTALLED:

    bowtie:              1.0.0-1            bioconda   
    bzip2:               1.0.6-1            conda-forge
    ca-certificates:     2017.7.27.1-0      conda-forge
    collectl:            4.0.4-1            bioconda   
    curl:                7.55.1-0           conda-forge
    fastool:             0.1.4-1            bioconda   
    jellyfish:           2.2.6-0            bioconda   
    krb5:                1.14.2-0           conda-forge
    libgcc:              5.2.0-0                       
    libssh2:             1.8.0-2            conda-forge
    openjdk:             8.0.121-1                     
    openssl:             1.0.2l-0           conda-forge
    parafly:             r2013_01_21-0      bioconda   
    perl:                5.22.0.1-0         conda-forge
    perl-app-cpanminus:  1.7039-pl5.22.0_3  bioconda   
    perl-file-find-rule: 0.34-1             bioconda   
    perl-module-build:   0.4214-pl5.22.0_3  bioconda   
    perl-number-compare: 0.03-pl5.22.0_1    bioconda   
    perl-text-glob:      0.11-pl5.22.0_0    bioconda   
    perl-threaded:       5.22.0-pl5.22.0_12 bioconda   
    samtools:            1.5-1              bioconda   
    slclust:             02022010-1         bioconda   
    trimmomatic:         0.36-5             bioconda   
    trinity:             2.4.0-2            bioconda   
    xz:                  5.2.3-0            conda-forge
    zlib:                1.2.11-0           conda-forge
```
</p></details>

Now it picked up the older `trinity=2.4.0-2` build which doesn't depend on `bowtie2`...

**Comment by bgruening** [comment] 2017-11-07 22:39
Try now!

**Comment by mbargull** [comment] 2017-11-07 22:44
Falls back to `trinity=2.4.0-1` 😐

**Comment by bgruening** [comment] 2017-11-07 22:52
I have this :(

<details><summary><code>
$  conda create --dry-run -n x -c conda-forge -c bioconda trinity 
</code></summary><p>

```
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /home/bag/miniconda2/envs/x:

The following NEW packages will be INSTALLED:

    bowtie:             1.2.1.1-py27pl5.22.0_0 bioconda   
    bowtie2:            2.3.3.1-py27pl5.22.0_0 bioconda   
    bzip2:              1.0.6-1                conda-forge
    ca-certificates:    2017.7.27.1-0          conda-forge
    certifi:            2017.7.27.1-py27_0     conda-forge
    collectl:           4.0.4-1                bioconda   
    curl:               7.55.1-0               conda-forge
    fastool:            0.1.4-1                bioconda   
    jellyfish:          2.2.6-0                bioconda   
    krb5:               1.14.2-0               conda-forge
    libgcc:             7.2.0-h69d50b8_2                  
    libgcc-ng:          7.2.0-h7cc24e2_2                  
    libssh2:            1.8.0-2                conda-forge
    libstdcxx-ng:       7.2.0-h7a57d05_2                  
    ncurses:            5.9-10                 conda-forge
    openjdk:            8.0.121-1                         
    openssl:            1.0.2l-0               conda-forge
    parafly:            r2013_01_21-0          bioconda   
    perl:               5.22.0.1-0             conda-forge
    perl-app-cpanminus: 1.7039-pl5.22.0_3      bioconda   
    perl-module-build:  0.4214-pl5.22.0_3      bioconda   
    perl-threaded:      5.22.0-pl5.22.0_12     bioconda   
    pip:                9.0.1-py27_0           conda-forge
    python:             2.7.14-1               conda-forge
    readline:           6.2-0                  conda-forge
    samtools:           1.5-1                  bioconda   
    setuptools:         36.6.0-py27_1          conda-forge
    slclust:            02022010-1             bioconda   
    sqlite:             3.13.0-1               conda-forge
    tbb:                2018_20170919-0        conda-forge
    tk:                 8.5.19-2               conda-forge
    trimmomatic:        0.36-5                 bioconda   
    trinity:            2.4.0-5                bioconda   
    wheel:              0.30.0-py_1            conda-forge
    xz:                 5.2.3-0                conda-forge
    zlib:               1.2.11-0               conda-forge
```
</p></details>

**Comment by mbargull** [comment] 2017-11-07 23:11
xD well, that's kinda funny. If I add `python=2` or `python=3` to the package list, I get the same package plan for each case in Miniconda2 and Miniconda3. If only `trinity` is requested, then I get `trinity=2.4.0-1` for Miniconda3 but for Miniconda2 I get -- just like you did -- `trinity=2.4.0-5` plus `python` etc.

**Comment by lparsons** [comment] 2017-11-08 15:58
So, could/should we mark some older trinity 2.4.0 builds as broken, to ensure conda picks up the correct ones? Doesn't resolve the underlying issue, but might make some installations work again.

**Comment by mbargull** [comment] 2017-11-10 15:52
We could try to also flag `2.4.0-0` and `2.4.0-1` as broken for now. @bgruening: Thoughts?

**Comment by mcg1969** [comment] 2017-11-30 02:53
Please see my later posts in #6296. In short, yes, something needs to be done about the broken `trinity` builds. I list 5 options here, but I think for this particular channel I would recommend removing them or at least moving them to a `broken` or `archive` channel label.

While the feature work in #6296 avoids the problem for _particular_ recipes, the fact that I can do `conda install trinity==2.4.0 bowtie=2.2.5=0` indicates that it doesn't truly solve the problem.

**Comment by mbargull** [comment] 2017-11-30 13:44
> the fact that I can do conda install trinity==2.4.0 bowtie=2.2.5=0 indicates that it doesn't truly solve the problem.

If Conda's default behavior would be to ignore older builds, then I'd argue being able to install those builds *iff they are explicitly requested* just a feature for reproducibility 😄. Though you made some good points in https://github.com/conda/conda/pull/6296#issuecomment-348050481 as to why we can't change the default behavior any time soon.

> moving them to a broken or archive channel label, so they aren't visible to conda in normal circumstances.

Yes, looks like this is the option we should/have to go for now.

**Comment by johanneskoester** [comment] 2017-11-30 13:54
Maybe I missed something, but are we talking about the bowtie2 package? There, version 2.2.5=0 is already marked as broken: https://anaconda.org/bioconda/bowtie2/files?version=2.2.5

Hence, the problem should be gone now?

**Comment by mbargull** [comment] 2017-11-30 14:00
Yes, that's fine. I believe @mcg1969 meant that only as a general example.

Currently `bowtie2` doesn't block a `conda install trinity` anymore. Now it's just the older builds of `trinity 2.4.0` which didn't declare a `bowtie2` and hence a transitive dependency on `python`.
So for `trinity`,
> flag 2.4.0-0 and 2.4.0-1 as broken for now

**Comment by mcg1969** [comment] 2017-11-30 14:06
Ah, OK, so is this issue still open as an example of other issues? (It’s an honest question, it’s not my issue tracker!) I do want to make sure that important channels like bioconda are doing the right thing with broken builds.

**Comment by johanneskoester** [comment] 2017-11-30 14:09
Ok, I just marked trinity 2.4.0-{0,1} as broken. Hence, I would say this one can be closed once somebody has confirmed it works now.

**Comment by johanneskoester** [comment] 2017-11-30 14:15
@mcg1969 we are now labelling broken stuff as broken. However, it is not ideal (as I outlined before in the issue on conda/conda), because this way these builds cannot be installed from environments anymore. But sometimes people have old environments which worked fine for them because they, e.g., pinned many dependencies manually...

**Comment by mbargull** [comment] 2017-11-30 14:16
@johanneskoester: Thanks, `conda create -n trinity trinity` now uses the newest build, i.e., issue resolved!

@mcg1969: This was still open since it hadn't been completely resolved, yet. Although this issue had only one underlying cause, the problem got manifested twice, once for old builds of `bowtie2` and once for those from `trinity` itself. For the u underlying cause, see: https://github.com/conda/conda/issues/6269#issuecomment-344077631

**Closed** 2017-11-30 14:17 UTC
Labels: bug

**Comment by mcg1969** [comment] 2017-11-30 14:20
@johanneskoester I hear you about the disadvantage of removal/archiving. We are actively working on a way to let channel maintainers “patch” metadata for broken packages.

**Comment by johanneskoester** [comment] 2017-11-30 14:30
@mcg1969  I'm not sure I get the patching. Wouldn't that be equivalent to fixing the package but not increasing the build number and then uploading it again?

**Comment by mbargull** [comment] 2017-11-30 14:38
I'll have to admit that I'm not too fond of that "patching" idea. Patching existing packages/builds themselves I'd refuse steadfastly and patching the channel's metadata.. well, depends on how easily one could maintain and transfer that information -- but it doesn't sound too convincing to me either, for now.
What I currently have in mind is something bluntly like: If the user (somehow explicitly) indicates they exactly want to replicate an environment of packages, then include some labels like `broken` in the search, i.e., replace
`conda create -n env -c bioconda --i-want-replication-pleease  package=version=some_broken_build`
with
`conda create -n env -c bioconda -c bioconda/label/broken  package=version=some_broken_build`

**Comment by johanneskoester** [comment] 2017-11-30 14:49
@mbargull yes, I think this could even happen automatically, on a per package bases. If one of the explicitly requested targets is not available in the main label, try the broken label.

**Comment by mcg1969** [comment] 2017-11-30 15:44
I understand the reluctancance, and we have explored a variety of solutions to the broken metadata problem. But I'm telling you, as long as broken metadata lives in a channel, the user experience suffers. One of the key philosophies of conda over more "wild west" packaging ecosystems is that we package maintainers absorb pain so that package users do not have to.

For now you need to _assume_ that all available builds of a package are candidates for installation by conda, and build your channel maintenance strategy accordingly.

As for the "patching" approach in particular, what we are referring to is a way to specify a "diff" between the metadata buried in the tarball and the corrected metadata. If you choose, you can use it in a "blunt" manner to simply mark a package as broken/obsolete, and that's fine. But you can also choose to simply correct a dependency list to enable a perfectly functioning package to continue to be installable under corrected circumstances. Either way, users that wish to exactly reproduce an environment, down to the build numbers and MD5 signatures, still get to do so---and those creating new environments can remain protected against broken environments.

It is important to understand that packages can _become_ broken. That is: they can start out perfectly functioning for every possible conda recipe, and then due to _additions to the package ecosystem_, that introduce incompatibilities, things can break.

**Comment by johanneskoester** [comment] 2017-11-30 15:59
@mcg1969:

> As for the "patching" approach in particular, what we are referring to is a way to specify a "diff" between the metadata buried in the tarball and the corrected metadata. If you choose, you can use it in a "blunt" manner to simply mark a package as broken/obsolete, and that's fine. But you can also choose to simply correct a dependency list to enable a perfectly functioning package to continue to be installable under corrected circumstances. Either way, users that wish to exactly reproduce an environment, down to the build numbers and MD5 signatures, still get to do so---and those creating new environments can remain protected against broken environments.

So, isn't this patching already possible now? I fix the dependencies, but don't increase the build number, and then I upload the package again, overwriting the broken one?

**Comment by mcg1969** [comment] 2017-11-30 16:08
If you unpack the tarball, fix the metadata, rebuild the tarball, and re-upload, yes, that will work.

That also changes the MD5 signature, which disturbs some people who really track that closely. People shouldn't care about this as much as they do---MD5 signatures are for download verification, not security. But it is what it is.

The "patching" approach is different. What that ends up doing, effectively, is changing what gets put into "repodata.json". Currently, your channel's repodata file is built simply by extracting the metadata from all of your tarballs. The new approach would combine that "raw" repodata with a set of "patches" that introduce corrections.

We do this kind of thing already for the defaults channel. For architectural reasons this capability is not yet available to all Anaconda channels, but we are working to make that possible.

Again, you can use it as a "blunt" instrument if you want, just marking broken builds as obsolete, so they won't appear in new installs. But if it's sufficiently easy to do, you may choose to do what we do, and _correct_ metadata so that an entirely functioning package can be restored to functionality.

**Comment by johanneskoester** [comment] 2017-11-30 16:16
@mcg1969 I don't think this is something we would use here. I think it would be better for us to just rebuild the package without increasing the build number. This way, it runs through our entire test pipeline and we are sure it really works. Plus, we have recipe and package in sync, and the git history properly reflects the changes.

This raises one important question though: so far, we used build numbers for fixes and improvements. If we go for that strategy, we would need to come up with an idea how to properly distinguish the two, so that for fixes, we don't increase the build number anymore.

**Comment by mbargull** [comment] 2017-11-30 16:36
> So, isn't this patching already possible now? I fix the dependencies, but don't increase the build number, and then I upload the package again, overwriting the broken one?

> If you unpack the tarball, fix the metadata, rebuild the tarball, and re-upload, yes, that will work.
>
>That also changes the MD5 signature, which disturbs some people who really track that closely. People shouldn't care about this as much as they do---MD5 signatures are for download verification, not security. But it is what it is.

> I think it would be better for us to just rebuild the package without increasing the build number. This way, it runs through our entire test pipeline and we are sure it really works. Plus, we have recipe and package in sync, and the git history properly reflects the changes.

Well, if we were concerned about security, we'd have to do a lot of other things, starting by signing packages etc. pp. 😆
However, from my POV, looking at checksums is valuable to us since we are interested in reproducible (scientific) results. Checksums offer a very simple, yet effective manner to tell someone if something changed although it wasn't supposed to. Hence, not modifying existing packages lets us do exactly that. It just depends on how pedantic we want to be about that manner when we are looking at the built packages only...

I haven't read and pondered about all you wrote, but I'd just like to add the following: For now you only considered older/newer/broken builds concerning metadata/dependencies. But that is only one, albeit likely common aspect. Since Conda is a binary package manager, the built files, i.e. package content, itself can change in newer builds, e.g., through changed compiler options and the like. Those cases just cannot be "fixed" by metadata updates.

**Comment by mcg1969** [comment] 2017-11-30 17:00
> If we go for that strategy, we would need to come up with a guideline how to properly distinguish the two, so that for fixes, we don't increase the build number anymore.

@johanneskoester indeed, given our experience understanding the varied issues with build number management, metadata patching, etc., I've found that build numbers are actually less useful than the original designers of conda thought they might be.

But what @mbargull said here is absolutely true:

> Since Conda is a binary package manager, the built files, i.e. package content, itself can change in newer builds, e.g., through changed compiler options and the like. Those cases just cannot be "fixed" by metadata updates.

Obviously anything that _does_ require a new _build_ suggests a bump in a build number. And yet: this is exactly the kind of circumstance that explains why you can't just force people to accept the latest build! For instance, what if someone has a functioning environment with the "old" compiler settings, and we know that packages build with the new settings will break. Then ideally, we would ensure that our dependencies prevent that mixture from happening---and that user will continue to need to install the old build. 

So then you say, "well, then we modify the rule: they should be forced to install the latest _compatible_ build." But that is, in fact, _what happens right now._

**Comment by johanneskoester** [comment] 2017-12-01 09:27
> So then you say: "well, then we modify the rule: they should be forced to install the latest compatible build." But that is, in fact, what happens right now.

@mcg1969 yes, I agree. It makes absolute sense to have build numbers to introduce changes in the build (different flags, different compiler and so on), and the solver should be able to choose from them. I also think it is quite good at it at the moment, apart from those hiccups caused by the feature which currently does not properly consider the channel priorities.

However, when I look at conda build 3 and the new hash build strings, this means, if I am not mistaken, that fixing a dependency will introduce a new hash, so that it is not anymore possible to rebuild with fixes and keep the original build string, right? This might be also one reason why you prefer the "patching" of the repodata? But then, it is not always obvious how to patch dependencies while getting still exactly the same result as before, while the package still worked.

**Conclusion:**  
Because of all these difficulties, I think for bioconda it would make sense to simply label stuff as broken and to say: "if you pin in an environment, only pin the version number, not the build string. We cannot guarantee that all build numbers/strings will always be available."

**Comment by mcg1969** [comment] 2017-12-01 13:22
Our preference for patching came long before the hashes were introduced.

And frankly, I would not be concerned about "getting still the exactly the same result as before". Even _without_ broken builds and patching you will not get the same result from day to day, as other channel builders (including us) update their channels with new versions and builds of packages that you depend on. That said, you can always make a case-by-case judgement call, depending on the type of fix a broken package calls for. If, for instance, it simply means putting an upper bound on the version number of a dependency (because the latest major release broke your package), that's a very good choice. If it's just plain broken, well, give it an impossible-to-satisfy dependency so it is never installable (e.g., `python <0`), or move it to a broken channel.

That's very good advice about pinning to a version and not a build.

**Comment by johanneskoester** [comment] 2017-12-01 14:36
@bioconda/core: please consider to parse above interesting discussion. The bottom line is:
we cannot rely on build numbers to avoid broken packages being pulled by the conda solver. The only feasible solution for us is to label packages as broken consequently. This should happen along with a statement about sustainability on the homepage, saying that we guarantee versions, but not builds to be kept, and a clear instruction on the homepage to create conda environments without pinning build numbers.

I will modify our docs accordingly. @daler, maybe we can think of a bioconda-utils based mechanism to automate the labelling.
