### ISSUE TITLE
bioconda installed R package is much slower than natively installed

### ISSUE THREAD

**Issue by benjjneb** [bioconda/bioconda-recipes#5457] opened 2017-08-07 16:27 UTC
The recipe for the dada2 R package (https://github.com/bioconda/bioconda-recipes/tree/master/recipes) is much slower, as much as 20x slower, than the same package version installed via the normal R package manager (https://github.com/qiime2/q2-dada2/issues/74),

This performance critical parts of this package are written in C/C++, and in parts depend on gcc/llvm vectorizing parts of the code. When profiling the conda-installed version and the native installation, it seems that these parts of the code are those slowing down the most.

Would I be correct to think that there is an issue here where the compilation of the C code is defaulting to do no or few optimizations? If so, how can I fix that, and make the compilers perform O2 or O3-level optimizations for reasonably recent architectures (eg. SSE3 and above)?

**Comment by zachcp** [comment] 2017-08-08 19:44
HI @benjjneb ,

I wrote the original recipe as well as the R-Rcppparallel recipe. I struggled a bit to get them to compile at all ... (at least thats faster than not running at all!). But in all seriousness, I am not really sure how to pass compiler options into  R - I was assuming the R CMD INSTALL took care of that aspect of the compilation process but apparently not.   I can take a look into this but perhaps @bgruening may have some insight.

zcp

**Comment by benjjneb** [comment] 2017-08-09 13:45
Thanks again for putting this together @zachcp It's definitely better than not running at all!

We didn't run into this slowdown issue until recently, but are revisiting to try to fix it since there are quite a few people using this conda recipe via QIIME2 to run analyses, and this slowdown is significant on larger datasets.

I think @brwnj also bumped the package to the new bioconductor version, any wisdom that might help us get a handle on what's going on here?

**Comment by zachcp** [comment] 2017-08-09 15:30
Just had a thought - does native compilation require make/automake/etc? Perhaps whats happening is in the absence of the build tools at compilation time it defaults to standard make. Perhaps we need only add the appropriate build tools as a dependency during the build.  (will look into later.)

**Comment by bgruening** [comment] 2017-08-09 15:49
@benjjneb @zachcp thanks for bringing this up! 
This is the commandline what we use to compile the package: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bioconductor-dada2/build.sh

@benjjneb can you use this as well and see if this already speeds things up for you? Otherwise tweaking this command is allowed and we could boost performance by this. Other idea, are you using mkl or similar stuff that we need to define as dependency?

**Comment by zachcp** [comment] 2017-08-09 16:20
@bgruening  if there are specific optimizations used by R - does R need extra build tools available to it? It looks like both [dada2](https://github.com/benjjneb/dada2/blob/master/src/Makevars) and [RcppParallel](https://github.com/RcppCore/RcppParallel/blob/master/src/Makevars) use Makevars to pass in variables.  I'm thinking that conda may not use these for some reason.

**Comment by bgruening** [comment] 2017-08-09 16:33
Mh not sure about this. But keep in mind that the compilation happens in a Docker container so all system dependent optimizations are useless for now.

**Comment by epruesse** [comment] 2017-08-16 03:35
Hi @benjjneb,

The vectorizing capability of GCC/LLVM is something that IIRC has evolved a lot recently, so with the default bioconda GCC I wouldn't expect too much. You could install GCC via conda and use the GCC vectorizer debug flags to figure out how your code needs to look so that the older GCC will spot the parts that can be vectorized... rather painful process, though. I've found that hand-coding the SSE stuff is in the end easier/more reliable than maintaining C/C++ that GCC will correctly vectorize.

Having a package for a more modern GCC is tricky. In theory it should be possible as long as the ABI stays the same.

W.r.t. CPU capabilities like AVX or SSE3, a locally with "native" flags compiled software will always be fastest. The next closest thing is shipping several variants of the code and selecting on the machine which should be run. One option is simply multiple binaries, as e.g. done with `raxmlHPC-SSE3` vs `raxmlHPC-AVX` etc, another is to do this in the binary in your own code, selecting different functions. VSEARCH e.g. has some SSE optimizations that are selected at runtime. Given that you are embedded in R and can't switch binaries, and given that you are compiled on a host that may not have SSE/AVX, the long-term easiest way might be to actually hand-code your SSE parts. (I know, no-where nearly as neat as just letting the compiler do that work).

Briefly checking your code -- are the parts in question a Needleman-Wunsch DP aligner? There are a few vectorized NW implementations out there, e.g. in VSEARCH under GPLv3. They may actually turn out to be even faster than the GCC vectorized implementation in dada2.

**Comment by epruesse** [comment] 2017-08-16 03:39
@bgruening I've got a similar issue with SINA btw. The conda-compiled version is nearly an order of magnitude slower than the locally compiled one. Same thing -- C++ code written to be vectorizable by the compiler, so a modern compiler makes a big difference. Considering that compute cycles have started to cost actual money for many of us, tackling this more comprehensively throughout bioconda might become necessary soon. Even if it's just a lot of maintainer docs, and maybe some helper scripts to switch binaries around depending on host.

**Comment by bgruening** [comment] 2017-08-16 06:54
There are some new packages for GCC in the making that can be tested :)
Let me know if you are up to this and I will search for the repo. A new GCC package and the new conda-build-3 will hopefully happen this year.

**Comment by benjjneb** [comment] 2017-08-17 14:26
Thanks @epruesse these comments are very helpful.

> You could install GCC via conda and use the GCC vectorizer debug flags to figure out how your code needs to look so that the older GCC will spot the parts that can be vectorized

This would seem to be worth trying. Is my understanding correct that this means that bioconda installation is using gcc 4.8.5 (the version in `conda install gcc`)?

> One option is simply multiple binaries, as e.g. done with raxmlHPC-SSE3 vs raxmlHPC-AVX etc, another is to do this in the binary in your own code, selecting different functions. VSEARCH e.g. has some SSE optimizations that are selected at runtime.

Is it possible to simply direct bioconda to compile the binary for SSE3 and-up, at the cost of not supporting earlier architecture? This perhaps reveals another confusion on my part: Even with a new version of gcc, would the bioconda version still be slow because it would compile the code for base x86 (and hence not be able to vectorize things)?

> Briefly checking your code -- are the parts in question a Needleman-Wunsch DP aligner? There are a few vectorized NW implementations out there, e.g. in VSEARCH under GPLv3. They may actually turn out to be even faster than the GCC vectorized implementation in dada2.

The NW aligner, and the kmer distance check both are critical to overall performance and gain greatly from (auto-)vectorization. Unfortunately I have not to this point found a replacement NW aligner that serves our needs, if I recall correctly the VSEARCH implementation vectorizes across multiple queries against a target sequence (rather than w/in the DP matrix) and does not support banded alignments, and we make use of both features.

>  the long-term easiest way might be to actually hand-code your SSE parts. (I know, no-where nearly as neat as just letting the compiler do that work).

I'm hoping it doesn't come to this, as getting down to assembly code is really getting beyond my skillset, I don't have a comp-sci type background.

**Comment by epruesse** [comment] 2017-08-17 18:43
> Is it possible to simply direct bioconda to compile the binary for SSE3 and-up, at the cost of not supporting earlier architecture? This perhaps reveals another confusion on my part: Even with a new version of gcc, would the bioconda version still be slow because it would compile the code for base x86 (and hence not be able to vectorize things)?

This is a somewhat conceptual issue. For how many architectures do you optimize and do you distribute a unified binary package of some sort or many? Graphics card drivers for windows have become so huge because they pack variations upon variations, optimized for all kinds of scenarios. Java with it's JIT essentially implements a "compile on site" approach, mirroring what was responsible for the immense longevity of classic mainframe software. The Linux kernel actually patches itself on the go to adapt to the architecture it's running on! 

Since cluster environments are a target for conda and Bioconda, and those may comprise nodes with different CPU types, making "AVX support" an architecture or a conda "feature" would lead to lots of trouble. So building sub-architecture packages isn't really an option. Not unless someone builds something into conda that makes the `activate` script and everything connected with it to deal with sub-architectures.

Most code leverages highly optimized libraries to do the heavy lifting. E.g. using Numpy in Python you may end up using Intels MKL, which numpy can be built for. So the bulk of the computation is done by code that includes specific code paths for each architecture, probably hand tuned by people very knowledgeable in them. 

GCC has the `-mtune` and `-march` flags. The latter builds code that may only work on the specified architecture (and up), the former only "tunes" for the architecture given without dropping support. It does, however, not build "alternative" paths. ICC can do that, though, IIRC. I don't know about the license, but maybe having ICC in conda would be an idea.

The catch with Dada2 is the R integration. If it was a binary executable, I'd say build multiple variants and have a shell thingy pick the right ones. 

If you are ready to invest some time, you could implement a plugin system. Put the compute intensive functions into a separate dynamic library, build multiple versions of that and load it after checking CPU capabilities with `dlopen`.

Maybe it's worth checking into other R libraries. The issue must have occurred before.

**Comment by epruesse** [comment] 2017-08-17 18:47
> The NW aligner, and the kmer distance check both are critical to overall performance and gain greatly from (auto-)vectorization. Unfortunately I have not to this point found a replacement NW aligner that serves our needs, if I recall correctly the VSEARCH implementation vectorizes across multiple queries against a target sequence (rather than w/in the DP matrix) and does not support banded alignments, and we make use of both features.

Maybe the short read aligners then. More in line with Dada2's input data. BBMap has some C code for the JNI implementation of the actual alignment that is IIRC banded. It's limited to 600bp because for longer sequences the data would span into the next bigger CPU cache and speed drops drastically, but that shouldn't be an issue for Dada2 (pending shiny new sequencing tech). 

I'm sure Bowtie2 has some heavily optimized code there too. It's probably easier to integrate whatever they use than the BWA implementation.

**Comment by epruesse** [comment] 2017-08-17 18:50
> I'm hoping it doesn't come to this, as getting down to assembly code is really getting beyond my skillset, I don't have a comp-sci type background.

Well, it's not really assembly. You are down to the pointer arithmetic in Dada2 already. The SSE primitives are available as builtins, you just call those. The catch is that there isn't really any simple tutorial style documentation on SSE out there. Or at least I haven't found anything.

**Comment by benjjneb** [comment] 2017-08-19 12:15
Thanks again @epruesse one more question.

> GCC has the -mtune and -march flags. The latter builds code that may only work on the specified architecture (and up), the former only "tunes" for the architecture given without dropping support. It does, however, not build "alternative" paths. ICC can do that, though, IIRC. I don't know about the license, but maybe having ICC in conda would be an idea.
>
>If you are ready to invest some time, you could implement a plugin system. Put the compute intensive functions into a separate dynamic library, build multiple versions of that and load it after checking CPU capabilities with dlopen.

Let's assume I rewrote parts of my code w/ SSE intrinsics: Is it possible to get Bioconda to compile an R package that makes use of SSE commands? Or is that impossible because not every architecture supports SSE?

I'm just trying to get clarity on what is possible before I go too far into this rabbit hole!

ps: On the philosophy, it may be OK from my perspective to simply not support non-SSE3 architectures.

**Comment by yesimon** [comment] 2017-08-19 14:35
It's not possible to change the `-march` because conda is standardizing on an old `march` and correctness and maximum compatibility is the primary goal of conda. That's not to say that they have different `flavors` like for numpy.

The easiest option is to try `-mtune` with the minimal level that supports a specific feature that you need (SSE3). Alternatively, you can detect cpu flags from within C code to choose transparently (instead of relying on wrappers scripts or different binaries like raxml) https://stackoverflow.com/questions/6121792/how-to-check-if-a-cpu-supports-the-sse3-instruction-set

**Comment by benjjneb** [comment] 2017-08-20 02:12
So, I've rewritten one critical piece of the code with SSE intrinsics and put the explicit SSE implementation as an option behind a run-time check for SSE/SSE2 support. This seems to work when I test it locally. My forked recipe is checked into github and is passing travis: https://github.com/benjjneb/bioconda-recipes/tree/q2-dada2-recipe

However, where I'm stuck now is how to test the conda-built binaries. I would like to profile the performance of these binaries, since performance is the whole point here, but how? Is there a way to install the conda-build binaries (by CentOS5 I believe) short of getting the new recipe pulled into the main bioconda project?

ps: @yesimon do you know how I could specify the `-mtune` flag for C (C++11 actually) code in an R package?

pps: Broader question: Is there a suggested mechanism to warn users who install this package via bioconda that they are probably substantially degrading performance relative to the suggested install route?

**Comment by epruesse** [comment] 2017-08-20 02:14
> Let's assume I rewrote parts of my code w/ SSE intrinsics: Is it possible to get Bioconda to compile an R package that makes use of SSE commands? Or is that impossible because not every architecture supports SSE?

The header file should be there and the compiler supports it. You just need to do a check at runtime what the CPU can do and choose the right function to call (or use an `if`).

**Comment by epruesse** [comment] 2017-08-20 02:16
> Is there a way to install the conda-build binaries (by CentOS5 I believe) short of getting the new recipe pulled into the main bioconda project?

The binaries build with `simulate-travis.py` should end up in your `conda-bld` folder. You can install them with conda by specifying a path `conda install .../conda-bld/linux-64/dada2...tgz`.

**Comment by benjjneb** [comment] 2017-08-20 02:21
> The binaries build with simulate-travis.py should end up in your conda-bld folder. You can install them with conda by specifying a path conda install .../conda-bld/linux-64/dada2...tgz

Unfortunately that does not seem to be working. I tried doing that, and it fails silently (when I check the R package version in the conda environment, it is still the native version not the version of what shiould have been installed). Nothing shows up with `-v` or `-v -v` that indicates a problem.

This post (https://github.com/conda/conda/issues/5266) is the closest thing I've found with some first-pass googling, and didn't help solve this.

**Comment by epruesse** [comment] 2017-08-20 02:26
Got to pack for the eclipse. I'll look into it when I'm back. It's hard to tell why what's happening from afar. 

You could try `conda install -c local` with the package in the `conda-bld` folder (check with `conda info` that it's got the right folder.

**Comment by yesimon** [comment] 2017-08-20 07:11
You can try `--configure-args` like so:

`R CMD INSTALL --build . --configure-args="CFLAGS=-mtune=core2 CXXFLAGS=-mtune=core2"`

**Comment by benjjneb** [comment] 2017-08-26 03:38
So, after buildling locally, the following works to install the locally built package:

`conda install -c local /tmp/miniconda/conda-bld/osx-64/bioconductor-dada2-1.5.3.2-r3.3.2_0.tar.bz2`

But then when I try to test the package with `R -e "library('dada2');packageVersion('dada2')"` I get the following:

> > library('dada2');packageVersion('dada2')
> Loading required package: Rcpp
> Error in dyn.load(file, DLLpath = DLLpath, ...) : 
>   unable to load shared object '/Users/bcallah/miniconda3/envs/test2/lib/R/library/dada2/libs/dada2.so':
>   dlopen(/Users/bcallah/miniconda3/envs/test2/lib/R/library/dada2/libs/dada2.so, 6): Library not loaded: @rpath/libintl.8.dylib
>   Referenced from: /Users/bcallah/miniconda3/envs/test2/lib/R/library/dada2/libs/dada2.so
>   Reason: image not found
> In addition: Warning messages:
> 1: package ‘dada2’ was built under R version 3.3.2 
> Error: package or namespace load failed for ‘dada2’
> Execution halted
> 

Any ideas on the dll failure? I can confirm that the `dada2.so` is indeed there, in the expected path...

**Comment by benjjneb** [comment] 2017-08-26 19:21
> You can try --configure-args like so:
> 
> R CMD INSTALL --build . --configure-args="CFLAGS=-mtune=core2 CXXFLAGS=-mtune=core2"

Is there a way to specify these flags in the conda recipe?

**Comment by epruesse** [comment] 2017-08-27 16:45
Sure, you just change `$R CMD INSTALL --build.` to `$R CMD INSTALL --build . --configure-args="CFLAGS=-mtune=core2 CXXFLAGS=-mtune=core2`.

Whether that's ok is a policy question though, and AFAIK the current policy is to build packages that will work on < core2 as well.

Where do you have your recipe? I'll fork and see what I can do.

> Edit2: Finally got the locally built package to load by removing the package and first installing gettext from conda-forge, conda install -c conda-forge gettext

What is your channel order? `gettext 0.18` from defaults is broken, but the 0.18.1 from conda-forge should supersede it. You could pin that one, actually.

**Comment by epruesse** [comment] 2017-08-27 16:49
> Any ideas on the dll failure?
Long story short, `gettext 0.18` is broken. Upstream effectively bumped the SO version by accident. They took it back down in 0.18.1.

**Comment by benjjneb** [comment] 2017-08-27 22:14
> Where do you have your recipe? I'll fork and see what I can do.

Right now it is at https://github.com/benjjneb/bioconda-recipes/tree/q2-dada2-recipe

Any help very much appreciated! This is my first time navigating conda builds.

> Whether that's ok is a policy question though, and AFAIK the current policy is to build packages that will work on < core2 as well.

Is there a resource that lays out the current policies in any detail?

This is perhaps important because we have a very specific use-case in mind here -- we are trying to get a conda-installable version of dada2 specifically for use with the QIIME2 platform (tracking issue for that here: https://github.com/qiime2/q2-dada2/issues/74).

What I would like to do is to create a conda build of dada2 that uses a customized branch of the dada2 package that implements a couple things (especially explicit SSE vectorization) that aren't in the official Bioconductor release yet but that give major benefits given the limitations of these cross-platform builds. 

Would that be approved by bioconda? Would that have to be perhaps a different recipe name (i.e. not bioconductor-dada2 but something else)?

**Comment by epruesse** [comment] 2017-08-27 23:28
>What I would like to do is to create a conda build of dada2 that uses a customized branch of the dada2 package that implements a couple things (especially explicit SSE vectorization) that aren't in the official Bioconductor release yet.

Personal advice: don't do that to yourself! Maintaining one branch of a popular tool is already enough work. (SILVA still uses older versions of SINA in its pipeline and the website tools. I am hard pressed to find the time to even work on the current release, backports to older versions I simply can't do. Branches... ugh!)

I can see how you want the qiime module out so that all the qiime users can employ it easily and are currently ready to compromise heavily to make that happen ASAP. You'll waste precious time down the line maintaining those two branches, though. Also, the branches are likely to have at least slightly different results, yet papers are likely not to mention which branch was used, breaking "reproducible science" principles.

The cost of finishing your patches, releasing a new dada2 version, pushing it through Bioconductor to Bioconda to Qiime2 is only time delay. As far as I can tell it's still mainly Qiime1 that is used in production, with Qiime2 in early-adopter stage. If the q2-dada2 module works in principle, that's good enough for people testing it. Waiting for the performance upgrade for a month or two is fine.

**Comment by yesimon** [comment] 2017-08-28 16:37
@epruesse using `-mtune=core2` should generate two codepaths, one for march generic and one utilizing features for processors that support `core2` - which means it should still support older cpus.

**Comment by epruesse** [comment] 2017-08-28 16:43
@yesimon AFAIK gcc never generates alternative code paths. (Correct me if I'm wrong, it'd be neat, but IIRC only ICC does that). mtune only uses a different "model" of CPU instruction timings for optimizing the code.

@benjjneb @yesimon: Sorry, I didn't spot that you used only `mtune` but not `march`. `mtune` is fine, just put that into the `build.sh` if it helps any.

**Comment by yesimon** [comment] 2017-08-28 19:59
It appears you are right - `mtune` still generates fully compatible code so it will not use SSE. From GCC.

```
-mtune=cpu-type
Tune to cpu-type everything applicable about the generated code, except for the ABI and the set of available instructions. While picking a specific cpu-type schedules things appropriately for that particular chip, the compiler does not generate any code that cannot run on the default machine type unless you use a -march=cpu-type option. For example, if GCC is configured for i686-pc-linux-gnu then -mtune=pentium4 generates code that is tuned for Pentium 4 but still runs on i686 machines.
```

**Comment by epruesse** [comment] 2017-08-28 20:33
@benjjneb Both AMD's original x86-64 specification and Intel's variant of that include SSE2 with 16 XMM registers. Since conda builds only 64-bit code, you can safely assume that SSE2 is available on all conda target platforms.

(GCC also knows this of course and has -msse2 on automatically when building for x86-64).

**Comment by epruesse** [comment] 2019-03-21 18:55
Seems to be fixed by gcc7

**Closed by epruesse** 2019-03-21 18:55 UTC
