### ISSUE TITLE
bioconductor-genomeinfodb installation fails 

### ISSUE THREAD

**Issue by sprouffske** [bioconda/bioconda-recipes#13869] opened 2019-03-01 18:59 UTC
I can't install `bioconductor-genomeinfodb`, and it fails when running the post-link script. 

I've tried the installation a few times. Following is the relevant bit from a verbose attempt. The post-link script fails when attempting to download the data. 

```
INFO conda.core.link:_execute_actions(589): ===> LINKING PACKAGE: bioconda::bioconductor-genomeinfodbdata-1.2.0-r351_0 <===
  prefix=/home/sprouka1/miniconda3/envs/test_r
  source=/home/sprouka1/miniconda3/pkgs/bioconductor-genomeinfodbdata-1.2.0-r351_0

DEBUG conda.core.link:run_script(1030): for bioconda::bioconductor-genomeinfodbdata-1.2.0-r351_0 at /home/sprouka1/miniconda3/envs/test_r, executing script: $ bash -x /home/sprouka1/miniconda3/envs/test_r/.tmp1ih7a75z
DEBUG conda.gateways.subprocess:subprocess_call(48): executing>> bash -x /home/sprouka1/miniconda3/envs/test_r/.tmp1ih7a75z
INFO conda.gateways.subprocess:subprocess_call(56): $ bash -x /home/sprouka1/miniconda3/envs/test_r/.tmp1ih7a75z
==> cwd: /home/sprouka1/miniconda3/envs/test_r/bin <==
==> exit code: 1 <==
==> stdout <==
b'ERROR: post-link.sh was unable to download any of the following URLs with the md5sum 8fdbaf72a91aa676a3d521f0f307f10b:\nhttps://bioconductor.org/packages/3.8/data/annotation/src/contrib/GenomeInfoDbData_1.2.0.tar.gz\nhttps://bioarchive.galaxyproject.org/GenomeInfoDbData_1.2.0.tar.gz\nhttps://depot.galaxyproject.org/software/bioconductor-genomeinfodbdata/bioconductor-genomeinfodbdata_1.2.0_src_all.tar.gz\n'
==> stderr <==
```
When I picked a URL from the post-link script to manually download using `wget`, I was successful.

```
$ wget https://bioconductor.org/packages/3.8/data/annotation/src/contrib/GenomeInfoDbData_1.2.0.tar.gz
Proxy request sent, awaiting response... 200 OK
Length: 9186748 (8.8M) [application/x-gzip]
Saving to: “GenomeInfoDbData_1.2.0.tar.gz”
$ ls GenomeInfoDbData_1.2.0.tar.gz 
GenomeInfoDbData_1.2.0.tar.gz
```

Following is another unsuccessful attempt to install `bioconductor-genomeinfodb` without the extra verbosity.
```
$ conda --version
conda 4.6.7

$ conda create -n test-genomeinfodb -c bioconda bioconductor-genomeinfodb

Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /home/sprouka1/miniconda3/envs/test-genomeinfodb

  added / updated specs:
    - bioconductor-genomeinfodb


The following NEW packages will be INSTALLED:
  _r-mutex           pkgs/r/linux-64::_r-mutex-1.0.0-anacondar_1
  binutils_impl_lin~ conda-forge/linux-64::binutils_impl_linux-64-2.31.1-h6176602_1
  binutils_linux-64  conda-forge/linux-64::binutils_linux-64-2.31.1-h6176602_3
  bioconductor-bioc~ bioconda/noarch::bioconductor-biocgenerics-0.28.0-r351_1
  bioconductor-geno~ bioconda/noarch::bioconductor-genomeinfodb-1.18.1-r351_0
  bioconductor-geno~ bioconda/noarch::bioconductor-genomeinfodbdata-1.2.0-r351_0
  bioconductor-iran~ bioconda/linux-64::bioconductor-iranges-2.16.0-r351h14c3975_0
  bioconductor-s4ve~ bioconda/linux-64::bioconductor-s4vectors-0.20.1-r351h14c3975_0
  bwidget            pkgs/main/linux-64::bwidget-1.9.11-1
  bzip2              conda-forge/linux-64::bzip2-1.0.6-h14c3975_1002
  ca-certificates    conda-forge/linux-64::ca-certificates-2018.11.29-ha4d7672_0
  cairo              conda-forge/linux-64::cairo-1.14.12-h80bd089_1005
  curl               conda-forge/linux-64::curl-7.64.0-h646f8bb_2
  fontconfig         conda-forge/linux-64::fontconfig-2.13.1-h2176d3f_1000
  freetype           conda-forge/linux-64::freetype-2.9.1-h94bbf69_1005
  gcc_impl_linux-64  conda-forge/linux-64::gcc_impl_linux-64-7.3.0-habb00fd_1
  gcc_linux-64       conda-forge/linux-64::gcc_linux-64-7.3.0-h553295d_3
  gettext            conda-forge/linux-64::gettext-0.19.8.1-h9745a5d_1001
  gfortran_impl_lin~ conda-forge/linux-64::gfortran_impl_linux-64-7.3.0-hdf63c60_1
  gfortran_linux-64  conda-forge/linux-64::gfortran_linux-64-7.3.0-h553295d_3
  glib               conda-forge/linux-64::glib-2.56.2-had28632_1001
  graphite2          conda-forge/linux-64::graphite2-1.3.13-hf484d3e_1000
  gxx_impl_linux-64  conda-forge/linux-64::gxx_impl_linux-64-7.3.0-hdf63c60_1
  gxx_linux-64       conda-forge/linux-64::gxx_linux-64-7.3.0-h553295d_3
  harfbuzz           conda-forge/linux-64::harfbuzz-1.9.0-he243708_1001
  icu                conda-forge/linux-64::icu-58.2-hf484d3e_1000
  jpeg               conda-forge/linux-64::jpeg-9c-h14c3975_1001
  krb5               conda-forge/linux-64::krb5-1.16.3-h05b26f9_1001
  libcurl            conda-forge/linux-64::libcurl-7.64.0-h541490c_2
  libedit            conda-forge/linux-64::libedit-3.1.20170329-hf8c457e_1001
  libffi             conda-forge/linux-64::libffi-3.2.1-hf484d3e_1005
  libgcc-ng          conda-forge/linux-64::libgcc-ng-7.3.0-hdf63c60_0
  libgfortran-ng     pkgs/main/linux-64::libgfortran-ng-7.3.0-hdf63c60_0
  libiconv           conda-forge/linux-64::libiconv-1.15-h14c3975_1004
  libpng             conda-forge/linux-64::libpng-1.6.36-h84994c4_1000
  libssh2            conda-forge/linux-64::libssh2-1.8.0-h90d6eec_1004
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-7.3.0-hdf63c60_0
  libtiff            conda-forge/linux-64::libtiff-4.0.10-h648cc4a_1001
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h14c3975_1000
  libxcb             conda-forge/linux-64::libxcb-1.13-h14c3975_1002
  libxml2            conda-forge/linux-64::libxml2-2.9.8-h143f9aa_1005
  make               conda-forge/linux-64::make-4.2.1-h14c3975_2004
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  openssl            conda-forge/linux-64::openssl-1.1.1b-h14c3975_0
  pango              conda-forge/linux-64::pango-1.40.14-hf0c64fd_1003
  pcre               conda-forge/linux-64::pcre-8.41-hf484d3e_1003
  pixman             conda-forge/linux-64::pixman-0.34.0-h14c3975_1003
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h14c3975_1001
  r-base             conda-forge/linux-64::r-base-3.5.1-he45234b_1005
  r-bitops           conda-forge/linux-64::r-bitops-1.0_6-r351h96ca727_1002
  r-rcurl            conda-forge/linux-64::r-rcurl-1.95_4.11-r351h96ca727_1003
  readline           conda-forge/linux-64::readline-7.0-hf8c457e_1001
  tk                 conda-forge/linux-64::tk-8.6.9-h84994c4_1000
  tktable            pkgs/main/linux-64::tktable-2.10-h14c3975_0
  wget               pkgs/main/linux-64::wget-1.19.5-h20c2e04_0
  xorg-kbproto       conda-forge/linux-64::xorg-kbproto-1.0.7-h14c3975_1002
  xorg-libice        conda-forge/linux-64::xorg-libice-1.0.9-h14c3975_1004
  xorg-libsm         conda-forge/linux-64::xorg-libsm-1.2.3-h4937e3b_1000
  xorg-libx11        conda-forge/linux-64::xorg-libx11-1.6.7-h14c3975_1000
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.9-h14c3975_0
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.2-h14c3975_1007
  xorg-libxext       conda-forge/linux-64::xorg-libxext-1.3.3-h14c3975_1004
  xorg-libxrender    conda-forge/linux-64::xorg-libxrender-0.9.10-h14c3975_1002
  xorg-renderproto   conda-forge/linux-64::xorg-renderproto-0.11.1-h14c3975_1002
  xorg-xextproto     conda-forge/linux-64::xorg-xextproto-7.3.0-h14c3975_1002
  xorg-xproto        conda-forge/linux-64::xorg-xproto-7.0.31-h14c3975_1007
  xz                 conda-forge/linux-64::xz-5.2.4-h14c3975_1001
  zlib               conda-forge/linux-64::zlib-1.2.11-h14c3975_1004


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(543): An error occurred while installing package 'bioconda::bioconductor-genomeinfodbdata-1.2.0-r351_0'.
LinkError: post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.0-r351_0
running your command again with `-v` will provide additional information
location of failed script: /home/sprouka1/miniconda3/envs/test-genomeinfodb/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: done

LinkError: post-link script failed for package bioconda::bioconductor-genomeinfodbdata-1.2.0-r351_0
running your command again with `-v` will provide additional information
location of failed script: /home/sprouka1/miniconda3/envs/test-genomeinfodb/bin/.bioconductor-genomeinfodbdata-post-link.sh
==> script messages <==
<None>
```

I'm not sure what's going on. It seems like a recipe issue, but maybe it is something else?

**Comment by nsoranzo** [comment] 2019-03-03 02:25
Duplicate of #13846.

**Closed by nsoranzo** 2019-03-03 02:25 UTC
